### ISSUE TITLE
Segfault when enabling disk-buffer on 3.8.1

### ISSUE THREAD

**Issue by clausa** [balabit/syslog-ng#1198] opened 2016-09-07 09:44 UTC
Trying to enable disk-buffer in syslog-ng 3.8.1 eventually results in syslog-ng segfaulting :-(

Syslog-ng is used to collect syslog from network, add a few SDATA key/value pairs and forward to Graylog as RFC-5424 syslog - as well as save a local copy to a disk archive.

We have seen a number of times that syslog-ng segfaults since enabling disk-buffers.
Trying to restart syslog-ng results in a segfault.
Removing the disk-buffer files from /var/lib/syslog-ng/ allow syslog-ng to start again.
Disabling disk-buffer configuration in the destination() allows syslog-ng to start again.

Have tried with reliable(yes) and reliable(no) - same issue.

Below is the relevant config as well as the output from GDB run on the coredump.

Please let me know if more info is needed.

```
source s_syslog_udp {
  syslog(
    ip(0.0.0.0)
    port(1514)
    log_iw_size(1100000)
    max-connections(10000)
    so-rcvbuf(268435456)
    transport("udp")
  );
};

destination d_graylog_vmware {
  syslog("127.0.0.1"
    persist_name("vmware")
    port(7517)
    transport("tls")
    tls(
      ca-dir("/etc/pki/tls/cacerts")
      peer-verify(optional-untrusted)
    )
    disk-buffer(
#      mem-buf-length(10000)
      disk-buf-size(10000000000) # 10GB disk buffer
      reliable(yes)
    )
  );
};

destination d_filearchive {
  file("/data/logarchive/syslog-ng/tmp/${R_YEAR}/${R_MONTH}/${R_DAY}/${R_HOUR}/${SOURCEIP}.log"
  template("$(indent-multi-line ${MESSAGE})\n")
  flags(syslog-protocol)
  );
};

rewrite r_sdata_vmware {
set("${SOURCEIP}" value(".SDATA.NXLOG@47121.LogSource"));
set("${LOGHOST}"  value(".SDATA.NXLOG@47121.LogServer"));
set("${R_STAMP}"  value(".SDATA.NXLOG@47121.LogReceiveTime"));
set("vmware"  value(".SDATA.NXLOG@47121.Type"));
set("00xxxx" value(".SDATA.NXLOG@47121.AssetID") condition(netmask("192.168.0.1/32")));
set("00yyyy" value(".SDATA.NXLOG@47121.CustomerID") condition(netmask("192.168.0.1/32")));
set("zzzzz" value(".SDATA.NXLOG@47121.Location") condition(netmask("192.168.0.1/32")));
[ snip 1500 lines with conditional sets]
};

filter f_vmware { in-list("/etc/syslog-ng/lists/vmware.list", value("SOURCEIP")); };

log { source(s_syslog_udp); filter(f_vmware);     rewrite(r_sdata_vmware);     destination(d_graylog_vmware);     destination(d_filearchive); flags(flow-control,final); };

$ head /etc/syslog-ng/lists/vmware.list -n2
192.168.0.1
192.168.0.2
```

Exact version is: https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng38/epel-7-x86_64/00446223-syslog-ng/syslog-ng-3.8.1-1.el7.centos.x86_64.rpm

Also happens with: https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng38/epel-7-x86_64/00449829-syslog-ng/syslog-ng-3.8.1-2.el7.centos.x86_64.rpm

```
$ syslog-ng -V
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision:
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: disk-buffer,sdjournal,afstomp,json-plugin,cryptofuncs,graphite,cef,kvformat,add-contextual-data,dbparser,pseudofile,curl,csvparser,syslogformat,confgen,afsocket,afuser,date,linux-kmsg-format,system-source,basicfuncs,afamqp,affile,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```

GDB on coredump:

```
# gdb core.31270
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
[New LWP 31271]
[New LWP 31272]
[New LWP 31270]
Reading symbols from /usr/sbin/syslog-ng...Reading symbols from /usr/lib/debug/usr/sbin/syslog-ng.debug...done.
done.
Missing separate debuginfo for
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/17/a121b1f7bbb010f54735ffde3347b27b33884d
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `syslog-ng -F'.
Program terminated with signal 11, Segmentation fault.
#0  nv_registry_get_handle_flags (self=0xec8180, handle=3623901696) at lib/logmsg/nvtable.h:91
91    return stored->flags;
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.163-3.el7.x86_64 elfutils-libs-0.163-3.el7.x86_64 eventlog-0.2.13-4.el7.x86_64 glib2-2.42.2-5.el7.x86_64 glibc-2.17-106.el7_2.8.x86_64 ivykis-0.36.2-2.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-8.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libgcrypt-1.5.3-12.el7_1.1.x86_64 libgpg-error-1.12-3.el7.x86_64 libnet-1.1.6-7.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libuuid-2.23.2-26.el7_2.3.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 pcre-8.32-15.el7_2.1.x86_64 systemd-libs-219-19.el7_2.12.x86_64 tcp_wrappers-libs-7.6-77.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  nv_registry_get_handle_flags (self=0xec8180, handle=3623901696) at lib/logmsg/nvtable.h:91
#1  log_msg_append_format_sdata (self=self@entry=0x7f28d8005a00, result=result@entry=0x1cf72e0, seq_num=seq_num@entry=0)
    at lib/logmsg/logmsg.c:858
#2  0x00007f28e4d02479 in log_writer_format_log (self=self@entry=0x1e00580, lm=lm@entry=0x7f28d8005a00, result=0x1cf72e0)
    at lib/logwriter.c:923
#3  0x00007f28e4d030e4 in log_writer_write_message (self=self@entry=0x1e00580, msg=0x7f28d8005a00,
    path_options=path_options@entry=0x7f28df019a00, write_error=write_error@entry=0x7f28df0199fc) at lib/logwriter.c:1101
#4  0x00007f28e4d033c6 in log_writer_flush (self=0x1e00580, flush_mode=LW_FLUSH_NORMAL) at lib/logwriter.c:1205
#5  0x00007f28e4d034b7 in log_writer_work_perform (s=0x1e00580) at lib/logwriter.c:185
#6  0x00007f28e4d0507d in _work (self=<optimized out>) at lib/mainloop-io-worker.c:52
#7  0x00007f28e36efc67 in iv_work_thread_do_work () from /lib64/libivykis.so.0
#8  0x00007f28e36eefc3 in iv_run_tasks () from /lib64/libivykis.so.0
#9  0x00007f28e36f17dc in iv_main () from /lib64/libivykis.so.0
#10 0x00007f28e36efab4 in iv_work_thread () from /lib64/libivykis.so.0
#11 0x00007f28e36f2270 in iv_thread_handler () from /lib64/libivykis.so.0
#12 0x00007f28e34d6dc5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f28e3203ced in clone () from /lib64/libc.so.6
(gdb)
```

**Comment by mitzkia** [comment] 2016-09-12 11:45
Hi, 

I started to investigate, but can not reproduce your issue. 
Could you please minimalize your configuration (only for effected drivers).
The generated core and disk-buffers files also can help in investigation. Could you send (or share) them (of course if it is not contains any sensitive data) ?

**Comment by clausa** [comment] 2016-09-21 11:09
Hi,

Unfortunately sharing coredump and disk-buffer files in public would be problematic. :-/

Is there anything I can do locally to help debug this further?

**Comment by bkil-syslogng** [comment] 2016-09-21 15:04
Minimizing both the configuration and the number of factors to reproduce on your machine as @mitzkia had requested would still be great help.

**Comment by xytis** [comment] 2016-09-29 08:46
Seems like the same issue:
```
destination d_def {
    syslog(
            "<URL>"
            disk-buffer(
                mem-buf-size(2000)
                disk-buf-size(2M)
                reliable(yes)
                )
          );
};
```
Backtrace:
```
#0  nv_registry_get_handle_flags (self=0x23243d0, handle=1073756784) at lib/logmsg/nvtable.h:91
#1  log_msg_append_format_sdata (self=self@entry=0x7feb400031d0, result=result@entry=0x2357f80, seq_num=seq_num@entry=0) at lib/logmsg/logmsg.c:858
#2  0x00007feb77958479 in log_writer_format_log (self=self@entry=0x234da60, lm=lm@entry=0x7feb400031d0, result=0x2357f80) at lib/logwriter.c:923
#3  0x00007feb779590e4 in log_writer_write_message (self=self@entry=0x234da60, msg=0x7feb400031d0, path_options=path_options@entry=0x7feb4f37aa00,
    write_error=write_error@entry=0x7feb4f37a9fc) at lib/logwriter.c:1101
#4  0x00007feb779593c6 in log_writer_flush (self=0x234da60, flush_mode=LW_FLUSH_NORMAL) at lib/logwriter.c:1205
#5  0x00007feb779594b7 in log_writer_work_perform (s=0x234da60) at lib/logwriter.c:185
#6  0x00007feb7795b07d in _work (self=<optimized out>) at lib/mainloop-io-worker.c:52
#7  0x00007feb76345c67 in iv_work_thread_do_work () from /lib64/libivykis.so.0
#8  0x00007feb76344fc3 in iv_run_tasks () from /lib64/libivykis.so.0
#9  0x00007feb763477dc in iv_main () from /lib64/libivykis.so.0
#10 0x00007feb76345ab4 in iv_work_thread () from /lib64/libivykis.so.0
#11 0x00007feb76348270 in iv_thread_handler () from /lib64/libivykis.so.0
#12 0x00007feb7612cdc5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007feb75e59ced in clone () from /lib64/libc.so.6
```

**Comment by MrAnno** [comment] 2017-08-07 13:26
This has been fixed in 4d1f65b1435bdb8773a67e32b298ebb20db53124 (as a part of #1456). The reproduction is not trivial, since the problem is based on a race condition.

[syslog-ng-3.11.1](https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.11.1) and [syslog-ng-3.10.1](https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.10.1) contain the fix.

**Comment by presidento** [comment] 2017-08-08 09:01
If it is fixed, can we close this issue?

**Comment by MrAnno** [comment] 2017-08-08 09:49
It's been a year, so I think we can close this issue based on both backtraces and our findings.

@clausa @xytis Please reopen this ticket, if you experience the crash in [syslog-ng-3.11.1](https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.11.1).

**Closed** 2017-08-08 09:50 UTC
Labels: bug
