### ISSUE TITLE
Memory Leak in Syslog-NG 3.7.2

### ISSUE THREAD

**Issue by Roycohen** [balabit/syslog-ng#862] opened 2016-01-10 22:05 UTC
Hi Guys,

We have a deployment of syslog-ng where we connect to NGINX parse the log with JSON parser and make 2 log commands to local Redis.
As time goes, the syslog-ng consums a lot of memory and it is not freeing it unless we are restarting the process.
The syslog-ng version and modules are as follow:
syslog-ng 3.7.2
Installer-Version: 3.7.2
Revision:
Compile-Date: Jan  6 2016 15:57:02
Available-Modules: afsocket,dbparser,sdjournal,cryptofuncs,confgen,system-source,afamqp,afstomp,linux-kmsg-format,csvparser,pseudofile,kvformat,basicfuncs,syslogformat,afmongodb,afuser,json-plugin,redis,afprog,affile,graphite
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

The syslog-ng configuration file is as follow:

```
@version: 3.7
options {
    flush_lines(0);
    time_reopen(10);
    log_fifo_size(1000);
    chain_hostnames(off);
    use_dns(no);
    use_fqdn(no);
    create_dirs(no);
    keep_hostname(yes);
};

destination lpush_redis {
    redis(
        host("localhost")
        port(6379)
        command("LPUSH", "mixel", "${MSG}")
    );
};

destination hincrby_daily_redis {
    redis(
        host("localhost")
        port(6379)
        command("HINCRBY", "agger-pixel-daily#:#${bla}#:#${bli}#:#${blue}#:#${blam}#:#${blan}#:#${blay}#:#${blur}#:#${date}#:#${bate}#:#${gate}#:#${mate}#:#${hate}", "${bay}", "1")
    );
};

parser json_nginx {
    json-parser();
};

filter hash_events_filter {
    match(
        'bill|gill|dill|mill|jill|hill|nill' value(e)
    );
};

filter no_hash_events_filter {
    not match(
        'bill|gill|dill|mill|jill|hill|nill' value(e)
    );
};

source s_nginx_20 {
    pipe(
        "/srv/logs/access.log"
        program_override("nginx-access-log")
    );
};

filter f_nginx_20 {
    match(
        "nginx-access-log" value("PROGRAM")
    );
};

log {
    source(s_nginx_20);
    parser(json_nginx);
    filter(hash_events_filter);
    destination(lpush_redis);
};

log {
    source(s_nginx_20);
    parser(json_nginx);
    filter(no_hash_events_filter);
    destination(hincrby_daily_redis);
};
```

**Comment by bazsi** [comment] 2016-01-11 09:54
We had a redis specific leak, that has been fixed in the 3.6 branch but I
am not sure about 3.7

@ihrwein?

**Comment by ihrwein** [comment] 2016-01-11 11:37
It's not the same, 3.7.2 contains the patch: https://github.com/balabit/syslog-ng/blob/syslog-ng-3.7.2/modules/redis/redis.c#L142

@Roycohen Could you run syslog-ng under valgrind and attach the output log?
```
G_SLICE=always-malloc valgrind -v --log-file=valgrind.log --leak-check=full syslog-ng -F --enable-core
```

**Comment by Roycohen** [comment] 2016-01-16 17:37
I can try to set up an env where I can run it with valgrind. Currently it is running on production so there I can't do that.
Will update soon with the log file.
How much time do you need me to run it that way?

**Comment by ihrwein** [comment] 2016-01-16 22:04
Say, 10 minutes. I hope that's enough. Note, that syslog-ng will run with reduced performance under valgrind (just a guess, but it can be easily more than 10 times).

**Comment by Roycohen** [comment] 2016-01-17 12:37
I have run it on our staging environment which doesn't use the syslog-ng as our production env.
I have attached the output. Please let me know whether it sufficient.

[valgrind.txt](https://github.com/balabit/syslog-ng/files/93383/valgrind.txt)

**Comment by bazsi** [comment] 2016-01-17 16:21
This seems to be a partial output only. Syslog-ng as running under valgrind
has to be stopped so that valgrind has a chance to finish its report.

**Comment by Roycohen** [comment] 2016-01-19 21:38
Yea, you are right.
Will do that again and will send the input.

**Comment by ihrwein** [comment] 2016-01-25 09:38
@Roycohen Did you manage to collect the input? Thanks!

**Comment by ihrwein** [comment] 2016-02-01 10:12
@Roycohen Do you need our help to collect the valgrind logs? Thanks!

**Comment by Roycohen** [comment] 2016-02-29 19:00
Hi @ihrwein,
Sorry for my late response, had some other issues :)
I've tried to collect the log but it doesn't seems to write something.
G_SLICE=always-malloc valgrind -v --log-file=valgrind.log --leak-check=full syslog-ng -F --enable-core
It should write to the log while processing.
Do you have any command which run the syslog with valgrind on the background.

**Comment by ihrwein** [comment] 2016-03-01 10:27
@Roycohen No problem :)

I suggest to run valgrind and syslog-ng in foreground mode. You can detach (and later attach) a terminal if you start valgrind in `screen` or `tmux`.

Your proposed command line should work.

We would like to include the fix of your memleak in the upcoming syslog-ng 3.7.3 release.

**Comment by Roycohen** [comment] 2016-03-01 15:23
@ihrwein, yes, this is exactly what I've did.
Great Great Great, the sooner the better for us. We use syslog-ng for a lot of things :).
Please let me know if this file is OK.

[valgrind_out.txt](https://github.com/balabit/syslog-ng/files/153006/valgrind_out.txt)

**Comment by ihrwein** [comment] 2016-03-01 19:09
That's more than before but I think it's still not enough :( 

How many messages did you send to syslog-ng? It would be nice to find a workload which utilizes all log paths in your config (especially the Redis destination).

**Comment by Roycohen** [comment] 2016-03-02 16:52
I have attached the config file. You can see the path of the Redis destination.
I will enable the syslog debug on our production for couple of hours and will see the results.

**Comment by bkil-syslogng** [comment] 2016-03-10 09:46
@Roycohen We are still waiting for further information. As we've said above, unfortunately it works correctly when we tried, so we can't reproduce.

After memory usage reaches your point of tolerance, typing this might also give us more information regardless of using Valgrind:
pmap -XX $(pidof syslog-ng) > /tmp/pmap-$(date +%Y-%m-%dT%H%M).txt

When running Valgrind, please send in tons of messages through Redis, wait a few minutes, and only exit then. It could happen that you would need many minutes (hours?) of run under Valgrind. At exit, look for the lines "in use at exit:" and the lines below "LEAK SUMMARY:". We can only use your Valgrind output if you can see megabytes there.

**Comment by bkil-syslogng** [comment] 2016-03-10 09:47
@Roycohen Additionally to the data above, @ihrwein recommend that this tool can also give useful output in certain cases:
http://milianw.de/blog/heaptrack-a-heap-memory-profiler-for-linux

**Comment by Roycohen** [comment] 2017-01-26 11:26
Hi Guys,

I'm sorry for my late response.
I couldn't give you guys the debugging as we switched to another architecture...
I'm pretty sure that there is a memory leak.
You have the entire configuration to reproduce it. you need to send a lot of data to make it happen.

**Comment by furiel** [comment] 2018-03-20 15:36
I checked this old thread and I cannot reproduce the memory increase either. Though I checked with the latest version 3.14. I am closing this ticket now. Anyway if this problem reoccurs, please open a ticket with the new version, listing  libhiredis version, example message, and a more simplified config if possible (do we need two redis destinations, filters, can we use file or network source instead of pipe), and anything that could help reproduce the problem.

**Closed by furiel** 2018-03-20 15:36 UTC
Labels: bug
