### ISSUE TITLE
block regex argument results in syntax error

### ISSUE THREAD

**Issue by jszigetvari** [balabit/syslog-ng#2777] opened 2019-06-12 12:21 UTC
# syslog-ng

## Version of syslog-ng

OSE 3.21

## Platform

RHEL 7.6

# Issue

## Failure

While trying to create a config block that expects a regex as one of its parameters, I encountered a problem, that I wasn't able to work around.
The configuration snippets posted below result in syntax errors in config parsing time, but they should work just fine.

## Configuration

```
@version: 3.21
@include "scl.conf"
block root dummy-block (
		loopback-socket-path("`syslog-ng-root`/var/run/message-loopback.sock")
		loopback-name(loopback_internal)
		feeder-source()
		return-destination()
		field-name()
		content-filter()
    )
{
		log {
			filter {
				not match( "`content-filter`" value("list_element"));
			};
		};
};

dummy-block(
	feeder-source(s_feeder)
	return-destination(d_return)
	field-name("EVENT_USERNAME")
	content-filter("([^\\\/\:\*\?\"\<\>\|]{1,15}|[^\,\~\:\!\@\#\$\%\^\&\'\.\(\)\{\}\_ ]{2,255})\\[^\"\/\\\[\]\:\;\|\=\,\+\*\?\<\>]+")
)
```

A shortened version of the config, that produces the same error:

```

@version: 3.21

block root dummy-block (
      content-filter("")
)
{
	log {
		filter {
			not match( "`content-filter`" value("list_element"));
		};
	};
};

dummy-block (
      content-filter("[^\"]")
)
```

**Comment by jszigetvari** [comment] 2019-06-21 08:06
In the meantime got hold of a feature installer with the patch in question. 
The error message is now different, as I tried a more real-world config, that is less stripped-down.

The config now looks like this:
```@version: 7.0

block root placeholder_A (
	loopback-name(loopback_internal)
	feeder-source()
	return-destination()
	field-name()
	content-filter()
)
{
	options {
		time-reopen(1);
	};
	

	log {
		source(s_`loopback-name`);
		
		parser {
			kv-parser();
		};
		
		junction {
			channel {
				filter {
					not match( "`content-filter`" value("list_element"));
				};
				
				destination(d_`loopback-name`);
			};
			channel {
				filter {
					match( "`content-filter`" value("list_element"));
				};
				
				destination(d_`return-destination`);
			};
		};		
	};
};

placeholder_A(
	feeder-source(s_feeder)
	return-destination(d_return)
	field-name("EVENT_USERNAME")
	content-filter("([^\\\/\:\*\?\"\<\>\|]{1,15}|[^\,\~\:\!\@\#\$\%\^\&\'\.\(\)\{\}\_ ]{2,255})\\[^\"\/\\\[\]\:\;\|\=\,\+\*\?\<\>]+")
)
```

The error message is the following:
```
Error parsing filter expression, error compiling search pattern, error=Error while compiling PCRE expression, error=nothing to repeat, error_at=63 in block root placeholder_A() at test.conf:3:19:115-19:116:
14                      };
15      
16                      junction {
17                              channel {
18                                      filter {
19---->                                         not match( "([^\\/:*?\"<>|]{1,15}|[^,~:!@#$%^&'.(){}_ ]{2,255})\\[^\"/\\[]:;|=,+*?<>]+" value("list_element"));
19---->                                                                                                                                                      ^
20                                      };
21      
22                                      destination(d_loopback_internal);
23                              };
24                              channel {

Included from test.conf:42:1-47:2:
37                              };
38                      };
39              };
40      };
41      
42----> placeholder_A(
42----> ^^^^^^^^^^^^^^^
43---->         feeder-source(s_feeder)
44---->         return-destination(d_return)
45---->         field-name("EVENT_USERNAME")
46---->         content-filter("([^\\\/\:\*\?\"\<\>\|]{1,15}|[^\,\~\:\!\@\#\$\%\^\&\'\.\(\)\{\}\_ ]{2,255})\\[^\"\/\\\[\]\:\;\|\=\,\+\*\?\<\>]+")
47----> )
```

**Comment by Kokan** [comment] 2019-06-21 08:10
Well it is kinda different: `Error while compiling PCRE expression`, before that it did not even try to process as a PCRE :)

Could you please check if you use `filter` with the following regex, does it work ? or it just fails if passed into block before ?

**Comment by jszigetvari** [comment] 2019-06-21 08:14
It is in deed different, but from the error message it seems that most, if not all of my escape characters from the RegEx were removed, thereby possibly breaking it:

```
"([^\\\/\:\*\?\"\<\>\|]{1,15}|[^\,\~\:\!\@\#\$\%\^\&\'\.\(\)\{\}\_ ]{2,255})\\[^\"\/\\\[\]\:\;\|\=\,\+\*\?\<\>]+"
```
vs.
```
"([^\\/:*?\"<>|]{1,15}|[^,~:!@#$%^&'.(){}_ ]{2,255})\\[^\"/\\[]:;|=,+*?<>]+"
```

**Comment by Kokan** [comment] 2019-06-21 11:08
In fact the lexer now works as intended (meaning that the patchset from @bazsi is correct).
But we were lucky to trigger the `cfg_lexer_subst_invoke`, which does the argument substitution. (imho this old substitution functionality of syslog-ng is kinda overloaded and causes magical issues).

**Comment by bazsi** [comment] 2019-06-21 15:29
Well, I agree the substitution is somewhat obscure, on the other hand you are pasting the value inside a string, which means that we need to do obscure things to represent a string literal as part of another string.

I believe syslog-ng is working properly here, although the error messages could be improved.

1) the block argument is a syslog-ng string literal. In a string literal when you used double-quotes (e.g. ")  you can use backslashes to produce some non-printable characters (e.g. \n) and also to escape the quote character itself.  Note that string literals are processed by syslog-ng first AND THEN handed over to the regexp engine.

2) this means that you indeed want to pass a backslash to the regexp engine and you use double-quotes to delimit your string, you'll need to duplicate your backslashes. e.g. "\\." is a regexp that contains a single backslash and a dot.

3) in your sample above you are also escaping things that don't need escaping at least for the syslog-ng string literal. For instance you are escaping the forward slash in the first part of the string, which does not otherwise need escaping. When a sequence like this occurs, syslog-ng simply assumes the escaped character is standing on its own, so it removes the backslash. "\\\/" for syslog-ng means: a sequence of two characters, a backslash and a forward slash.

4) your complete string literal of "([^\\\/\:\*\?\"\<\>\|]{1,15}|[^\,\~\:\!\@\#\$\%\^\&\'\.\(\)\{\}\_ ]{2,255})\\[^\"\/\\\[\]\:\;\|\=\,\+\*\?\<\>]+" equals to this string value for syslog-ng: >>>([^\/:*?"<>|]{1,15}|[^,~:!@#$%^&'.(){}_]{2,255})\[^"/\[]:;|=,+*?<>]+<<< (I am using greater-than & less-than symbols  to delimit the string value, but within those it is the actual value of the string without any escaping. You can see that your initial "\\\/" sequence becomes >>>\/<<<

5) now given this value, we are pasting this into somewhere within the block using backticks. There are two cases:
  5a) when you are pasting this value at the token level (e.g. just `value` anywhere in the block not enclosed into quotes)
  5b) when you are pasting this value into a string literal (e.g. something like "`value`"), which you actually do

6) if you paste the value as part of a string, we need to re-escape it, so that by the time syslog-ng goes through the parsing again, it would see a string value that is seamlessly part of another string. That's where we add some escaping back, but not all of them, as not all of your characters require escaping.

I've changed your configuration like this:

```
--- etc/syslog-ng-block-arg.conf	2019-06-21 15:13:26.504730224 +0000
+++ etc/syslog-ng-block-arg2.conf	2019-06-21 15:13:13.304574454 +0000
@@ -25,7 +25,7 @@
 		junction {
 			channel {
 				filter {
-					not match( "`content-filter`" value("list_element"));
+					not match( `content-filter` value("list_element"));
 				};
 				
 				destination(d_`loopback-name`);
```

With that change, your string will be substituted to the block _exactly_ as you wrote it (as it is outside of quote characters), with that the error message will be:

```
Error parsing filter expression, error compiling search pattern >>>([^\/:*?"<>|]{1,15}|[^,~:!@#$%^&'.(){}_]{2,255})\[^"/\[]:;|=,+*?<>]+<<<, error=Error while compiling PCRE expression, error=nothing to repeat, error_at=62 in block root placeholder_A() at etc/syslog-ng-block-arg2.conf:5:19:151-19:152:
14      		};
15      		
16      		junction {
17      			channel {
18      				filter {
19----> 					not match( "([^\\\/\:\*\?\"\<\>\|]{1,15}|[^\,\~\:\!\@\#\$\%\^\&\'\.\(\)\{\}\_]{2,255})\\[^\"\/\\\[\]\:\;\|\=\,\+\*\?\<\>]+" value("list_element"));
19----> 					                                                                                                                                                 ^
20      				};
21      				
22      				destination(d_loopback_internal);
23      			};
24      			channel {

Included from etc/syslog-ng-block-arg2.conf:44:1-49:2:
39      			};
40      		};		
41      	};
42      };
43      
44----> placeholder_A(
44----> ^^^^^^^^^^^^^^^
45----> 	feeder-source(s_feeder)
46----> 	return-destination(d_return)
47----> 	field-name("EVENT_USERNAME")
48----> 	content-filter("([^\\\/\:\*\?\"\<\>\|]{1,15}|[^\,\~\:\!\@\#\$\%\^\&\'\.\(\)\{\}\_]{2,255})\\[^\"\/\\\[\]\:\;\|\=\,\+\*\?\<\>]+")
49----> )

```

Now if you look at the error trigger you can see, that the match() function will get an exact copy of your string. And the PCRE error message remains, simply because it is indeed the regexp that is at fault here.

**Comment by bazsi** [comment] 2019-06-21 15:35
I have improved the error messages somewhat in the same branch even though theoretically it is a separate "feature".

**Comment by bazsi** [comment] 2019-06-21 15:38
ah, the branch has already been merged. opening a new one.

**Comment by jszigetvari** [comment] 2019-06-21 15:49
Thank you Bazsi, I will test it some time during the weekend.

**Comment by jszigetvari** [comment] 2019-06-26 15:45
I'm getting a bit confused here. I tried the change you suggested first, ie removing the quotes from before and after the backticks in `not match(...`

Once I did that, I got the following:

```
Error parsing filter expression, syntax error, unexpected '(', expecting LL_IDENTIFIER or LL_STRING in block root field_from_EventData() at test.conf:187:74:19-74:20:
69                                      };
70      
71                                      junction {
72                                              channel {
73                                                      filter {
74---->                                                         not match( ([^\\/:*?\"<>|]{1,15}|[^,~:!@#$%^&'.(){}_ ]{2,255})\\[^\"\\/[]:;|=,+*?<>]+ value("list_element"));
74---->                                                                    ^
75                                                      };
76      
77                                                      rewrite {
78                                                              set(
79                                                                      "$( + ${i} 1 )"

Included from test.conf:310:1-315:2:
305                             };
306                     };
307             };
308     };
309     
310---> field_from_EventData(
310---> ^^^^^^^^^^^^^^^^^^^^^^
311--->         feeder-source(s_feeder)
312--->         return-destination(d_return)
313--->         field-name("EVENT_USERNAME")
314--->         content-filter("([^\\/:*?\"<>|]{1,15}|[^,~:!@#$%^&\'.(){}_ ]{2,255})\\[^\"\\/[]:;|=,+*?<>]+")                                                                                                                                
315---> )
```

**Comment by MrAnno** [comment] 2019-06-28 11:12
After fixing the user-errors in the regexp, we've found another lexer-related(?) bug:

Reproduction:
```
@version: 3.22

block root test_scl (
	content-filter()
)
{
	log {
		destination {
			file ("/dev/stdout"
				template("new line confuses lexer?!\n")
			);
		};

		filter {
			match( `content-filter` value("list_element"));
		};
	};
};

test_scl(
	content-filter("\"")
);
```
Removing the new line from the destination template makes syslog-ng start.

**Comment by MrAnno** [comment] 2019-08-14 12:44
I've opened a new issue from my comment above. I'm closing this one as the original issue has been fixed.

**Closed by MrAnno** 2019-08-14 12:44 UTC
Labels: bug
