### ISSUE TITLE
compile syslog-ng on Debian without python2 installed

### ISSUE THREAD

**Issue by mochrul** [balabit/syslog-ng#1831] opened 2017-12-30 22:02 UTC
# syslog-ng

## Version of syslog-ng

3.13.2

## Platform

Debian (unstable)

# Issue

If no python2 is installed, syslog-ng cannot be compiled.at least not in a Debian host.
This is mainly because the python command is only installed with the python2 but
not with python3. And the python binary is referenced multiple times in the source.

Twice in configure.ac (first with AC_PATH_PRG, secondly in a librabbitmq related check.
But after fixing this, there are some scripts which require the python binary:
```
$ git grep "env python"
lib/merge-grammar.py:#!/usr/bin/env python
modules/python/pylib/setup.py:#!/usr/bin/env python
tests/functional/func_test.py:#!/usr/bin/env python
```

**Comment by mochrul** [comment] 2018-01-01 20:58
Additionally, merge-grammar is not python3 compatible, so switching the shebang to python3.

```
Traceback (most recent call last):
  File "../../lib/merge-grammar.py", line 55, in <module>
    for line in fileinput.input():
  File "/usr/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/usr/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 68: ordinal not in range(128)
```

**Comment by Kokan** [comment] 2018-01-02 06:40
> Twice in configure.ac (first with AC_PATH_PRG, secondly in a librabbitmq related check.
But after fixing this, there are some scripts which require the python binary:

The python2 is hard dependency for compilation because of `merge-grammar.py`. So removing this check is not ok.

> This is mainly because the python command is only installed with the python2 but
not with python3. And the python binary is referenced multiple times in the source.

Should not be a default python in a path also in case of python3 ?

**Comment by mochrul** [comment] 2018-01-02 14:59
I'm not sure I'm understanding the question correctly, but no. If you do not install python2, then there won't be python command in anywhere on the system. Only python3.

**Comment by mochrul** [comment] 2018-01-03 20:52
The modules/python/pylib/setup.py is a red herring because that script is not called directly but through an interpreter, so the requested interpreter at the beginning of the file does not matter.

**Comment by Kokan** [comment] 2018-01-04 06:57
> I'm not sure I'm understanding the question correctly, but no. If you do not install python2, then there won't be python command in anywhere on the system. Only python3.

Yes, and I mean imho that is a bad practice. 

Like I install a version of gcc (or any other tool), and there is going to be a version binary and a symbolic link to the not versioned one. (Like in gentoo the `eselect` that's a nice approach.)

But anyway not that related.

To summarize this is rather a feature (so I marked it as an enhancement) not a bug.

**Comment by mochrul** [comment] 2018-01-04 08:24
I agree that this could be debatable, but the python community is on the same side as Debian.

https://www.python.org/dev/peps/pep-0394/

"The more general python command should be installed whenever any version of Python 2 is installed and should invoke the same version of Python as the python2 command (however, note that some distributions have already chosen to have python implement the python3 command; see the Rationale and Migration Notes below)."

**Comment by furiel** [comment] 2018-01-31 07:54
I found the root cause, it was an unicode problem :) The python script fails on á in Balázs in the copyright section. After adding encoding hooks to fileinput, open and print, syslogng compiles fine. I will create a patch.

**Comment by furiel** [comment] 2018-01-31 17:50
After looking more into the issue, it not a python3 problem, but invalid/missing locale configuration on the build machine.

Starting a docker container with ubuntu:xenial, with python3 installed:
```
# cat proba.txt 
áááááá
```
In the python interpreter
```
>>> open("proba.txt")
<_io.TextIOWrapper name='proba.txt' mode='r' encoding='ANSI_X3.4-1968'>
```
which show the detected encoding is invalid. And after iterating through the lines:
```
>>> for line in open("proba.txt"):
...     print(line)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```
we have the same error as in the description.

However after generating and setting the hungarian locales with:
```
# apt-get install locales
# locale-gen hu_HU.utf8
# export LANG=hu_HU.utf8
open("proba.txt")
<_io.TextIOWrapper name='proba.txt' mode='r' encoding='UTF-8'>
```
and the encoding is detected correctly.

Now with a little code added, I can enforce the utf8 encoding for file open. Probably we cannot expect the hungarian locales to be generated on a builder machine.

**Closed** 2018-02-14 09:49 UTC
Labels: enhancement
