### ISSUE TITLE
pull syslog-ng segment fault

### ISSUE THREAD

**Issue by Allen1218** [balabit/syslog-ng#2729] opened 2019-05-15 03:56 UTC
# segment fault
----------
this problem find in 3.16.1 version.
----
This problem is similar to this issue --- （https://github.com/buytenh/ivykis/issues/15）

----
I am based on this modification（https://github.com/buytenh/ivykis/pull/16/commits/a844abca43349739c36a4cdb7ea6f3bce560bd7f）。 After repaired, segment fault is disappeard.

But ，Brought a new problem。
```
Error parsing source statement, source plugin network not found in /home/syslog-ng/etc/syslog-ng.conf:
```

---

I tested on the latest version（syslog-ng 3.21.1），the segment fault still appearing.

----
Therefore, I want to understand the following two points：
1. I want to know whether the segmentation error has been fixed in the latest version?
2.  "source plugin network not found "--- What is the cause of this problem, and how to fix it？

thanks

**Comment by Kokan** [comment] 2019-05-15 06:45
1. I want to know whether the segmentation error has been fixed in the latest version?
So the first issue (segfault) is actually a duplicate of ths https://github.com/balabit/syslog-ng/issues/2263 ?
If so, this crash happens in ivykis, while your suggested commit is not on ivykis master, so it is not part of the syslog-ng either. (When it is, probably we should update onto that version.)

2. The most likely cause could be: the path where syslog-ng is looking for plugins it cannot find.
Other possible issue could be that the module/plugin is not compiled correctly.

In order to find out, what could be the issue please use the followings:
`syslog-ng -V`
This should print out both the list of modules (where `afsocket` should be present), and the path where it is looking for the modules.
You could check if that path contains the needed module.

If in the path there is a `libafsocket.so`but in the module list does not you could try to turn on debug, verbose, trace log to further investigate the root cause.
`syslog-ng --module-registry -dvt`
This should gave you more information why it cannot load the module.

**Comment by Allen1218** [comment] 2019-05-15 06:59
Indeed, my fisrt problem is a duplicate of this #2263.

**Comment by Allen1218** [comment] 2019-05-15 07:10
**The second problem.**

* Problem Description

```
./syslog-ng
Error parsing source statement, source plugin default-network-drivers not found in /home/syslog-ng/etc/syslog-ng.conf:
10              system();
11              internal();
12      };
13
14      source s_network {
15---->         default-network-drivers(
15---->         ^^^^^^^^^^^^^^^^^^^^^^^
16                      # NOTE: TLS support
17                      #
18                      # the default-network-drivers() source driver opens the TLS
19                      # enabled ports as well, however without an actual key/cert
20                      # pair they will not operate and syslog-ng would display a


syslog-ng documentation: https://www.balabit.com/support/documentation?product=syslog-ng-ose
contact: https://lists.balabit.hu/mailman/listinfo/syslog-ng

```

----
* syslog-ng -V

```
 ./syslog-ng -V
syslog-ng 3 (3.16.1)
Config version: 3.16
Installer-Version: 3.16.1
Revision:
Compile-Date: May 15 2019 02:30:45
Module-Directory: /home/syslog-ng/lib/syslog-ng
Module-Path: /home/syslog-ng/lib/syslog-ng
Available-Modules: xml,syslogformat,snmptrapd-parser,tfgetent,hook-commands,kvformat,afuser,add-contextual-data,afprog,afstomp,sdjournal,dbparser,pseudofile,disk-buffer,afsocket,basicfuncs,system-source,cryptofuncs,tags-parser,stardate,confgen,appmodel,graphite,date,cef,map-value-pairs,affile,linux-kmsg-format,csvparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: off

```

**Comment by Kokan** [comment] 2019-05-15 08:13
The `default-network-drivers` is not part of the afsocket/network module, but implemented as a `block` in the SCL. Your config should include the `scl.conf`, and you should have the scl file, for me it is in the `${install_prefix}/share/syslog-ng/include/scl/default-network-drivers/plugin.conf', you could look for the `default-network-drivers` directory.

**Comment by Kokan** [comment] 2019-05-21 17:09
As this is likely an issue of missing scl/include; and became inactive I'm closing this issue; please reopen if the issue is still persist.

**Closed by Kokan** 2019-05-21 17:09 UTC
