### ISSUE TITLE
geoip: Invalid database type GeoIP Country Edition warning message

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#1446] opened 2017-04-25 13:55 UTC
This is an really annoying warning(?) message:
"Invalid database type GeoIP Country Edition, expected GeoIP City Edition, Rev 1"

If I add the city edition instead then:
"Invalid database type GeoIP City Edition, Rev 1, expected GeoIP Country Edition"

bonus: the function itself works, just gives this message every time when a new message comes.

This message should not come, and especially not to stderr without any formatting (this is not a syslog-ng debug message).

```
pzolee@Thor-E5440:~/projects/syslog-ng-ose/install$ sbin/syslog-ng -Fe
syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
[2017-04-25T15:51:14.283711] WARNING: Configuration file format is newer than the current version, please specify the current version number (3.9) in the @version directive. syslog-ng will operate at its highest supported version in this mode;
[2017-04-25T15:51:14.283797] Plugin module not found in 'module-path'; module-path='/home/pzolee/projects/syslog-ng-ose/install/lib/syslog-ng', module='geoip'
[2017-04-25T15:51:14.303182] syslog-ng starting up; version='3.9.1'
[2017-04-25T15:51:16.984564] Syslog connection accepted; fd='14', client='AF_INET(127.0.0.1:41188)', local='AF_INET(0.0.0.0:1212)'
Invalid database type GeoIP Country Edition, expected GeoIP City Edition, Rev 1
[2017-04-25T15:51:16.984919] Syslog connection closed; fd='14', client='AF_INET(127.0.0.1:41188)', local='AF_INET(0.0.0.0:1212)'
[2017-04-25T15:52:10.216462] Syslog connection accepted; fd='14', client='AF_INET(127.0.0.1:41192)', local='AF_INET(0.0.0.0:1212)'
Invalid database type GeoIP Country Edition, expected GeoIP City Edition, Rev 1
[2017-04-25T15:52:10.216605] Syslog connection closed; fd='14', client='AF_INET(127.0.0.1:41192)', local='AF_INET(0.0.0.0:1212)'

```
reproduction:
start syslog-ng with the config below
send a message:echo "<38>Jan  1 14:45:22 95.108.142.138 prg00000[1234]: test message" | nc 127.0.0.1 1212

config:
```
@version: 7.0
@module geoip

options {
stats_freq(0);
keep_hostname(yes);
};

destination d_messages { file("/tmp/aaa" template("$(format-json --scope core --key geoip*)\n")); };

source s_tcp{tcp(port(1212));};

parser p_geoip { geoip( "${HOST}", prefix( "geoip." )
database("/usr/share/GeoIP/GeoIP.dat")
); };

log {
source(s_tcp);
parser(p_geoip);
destination(d_messages);
};

```

**Comment by faxm0dem** [comment] 2017-04-25 14:12
that's a duplicate of #663

**Comment by pzoleex** [comment] 2017-04-25 14:14
yeah, really. But not only when it does not match, this message comes always

**Comment by furiel** [comment] 2017-04-27 09:41
I quickly hacked around the code in my local environment to check what happens if we replace libgeoip with libmaxminddb. The good news is syslog-ng works fine with the newer version instead of deprecated libgeoip library. Of course one needs to use input files of compatible format: .mmdb instead of the original .dat.

**Comment by furiel** [comment] 2017-05-24 07:42
The pr above fixes the problem with the legacy geoip library. But we can still introduce the libmaxminddb besides that.

**Closed** 2017-06-27 09:00 UTC
Labels: enhancement
