### ISSUE TITLE
pdbtool merge: htmlentities break functionality

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#129] opened 2014-05-22 11:49 UTC
I have a `pdb` file which triggers an action on a given condition:
``` xml
<action condition='"${appacct.difference_dur}" &gt;= "604800"'>
```
`pdbtool merge` transforms this snippet into:
``` xml
<action condition='&quot;${appacct.difference_dur}&quot; &gt;= &quot;604800&quot;'>
```

Problem is, the condition now matches all events, even those where `${appacct.difference_dur} < 604800`.

**Comment by ihrwein** [comment] 2015-12-02 14:14
Hi!

Could you attach a minimalist merged xml file where the problem can be reproduced?

Thanks!

**Comment by faxm0dem** [comment] 2015-12-02 15:28
#### command
```
pdbtool merge --directory=/tmp/patterndb --glob=\*.pdb --pdb /tmp/patterndb.pdb
```

#### /tmp/patterndb/rrdtool.pdb
```xml
<patterndb version='4' pub_date='2014-03-10'>
	<ruleset name='rrdtool' id='REPLACE_UUID'>
		<description>generated by puppet</description>
		<patterns>
			<pattern>rrdcached</pattern>
		</patterns>
		<rules>
			<rule provider='wernli@in2p3.fr' id='2b8a2697-7205-4d8a-802f-1540e6af3eff'
			      context-id='rrdcached-lastupdate-${appacct.filename}'
			      context-scope='process'
			      class='software'>
				<patterns>
					<pattern>queue_thread_main: rrd_update_r @QSTRING:appacct.filename:()@ failed with status @ESTRING:appacct.status:.@ (@ESTRING:::@ illegal attempt to update using time @ESTRING:appacct.update_time: @when last update time is @ESTRING:appacct.last_time: @(minimum one second step))</pattern>
				</patterns>
				<values>
					<value name='appacct.difference_dur'>$(- ${appacct.last_time} ${appacct.update_time})</value>
				</values>
				<examples>
					<example>
						<test_message program="rrdcached">queue_thread_main: rrd_update_r (/srv/rrd/ccwsge0247.in2p3.fr/disk-sdb/disk_octets.rrd) failed with status -1. (/srv/rrd/ccwsge0247.in2p3.fr/disk-sdb/disk_octets.rrd: illegal attempt to update using time 1394206025 when last update time is 2660923375 (minimum one second step))</test_message>
						<test_values>
							<test_value name='appacct.filename'>/srv/rrd/ccwsge0247.in2p3.fr/disk-sdb/disk_octets.rrd</test_value>
							<test_value name='appacct.last_time'>2660923375</test_value>
							<test_value name='appacct.status'>-1</test_value>
							<test_value name='appacct.update_time'>1394206025</test_value>
						</test_values>
					</example>
				</examples>
				<actions>
					<action condition='"${appacct.difference_dur}" &gt;= "604800"'>
						<message inherit-properties='TRUE'>
							<tags>
								<tag>alert</tag>
							</tags>
						</message>
					</action>
				</actions>
			</rule>
		</rules>
	</ruleset>
</patterndb>
```

**Comment by ihrwein** [comment] 2015-12-08 13:28
@faxm0dem I tried to reproduce the bug but without success. I tried the following cases:
* use the above patterndb config
* use the above config and replace the action with `<action condition='&quot;${appacct.difference_dur}&quot; &gt;= &quot;604800&quot;'>`
* I tried different `appacct.difference_dur` values. Some were greater, some were less than `604800`.

Could you recheck it please with the current master? Maybe a patch solved this in the meantime. Or I can try this with `3.6`.

**Comment by faxm0dem** [comment] 2015-12-10 10:24
@ihrwein so the action's condition is correctly being honored?

**Comment by ihrwein** [comment] 2015-12-10 11:44
Yeah. Message was only generated when `difference_dur` wa greater or equal to 604800.

**Comment by faxm0dem** [comment] 2015-12-10 15:10
okay, I'll try to reproduce again hoping I was wrong

**Comment by ihrwein** [comment] 2016-01-20 13:49
@faxm0dem Did you manage to try it? :)

**Comment by pzoleex** [comment] 2016-09-02 11:21
Closed due to inactivity

**Closed by pzoleex** 2016-09-02 11:21 UTC
Labels: blocked, bug, help
