### ISSUE TITLE
patterndb duplicate parser node in radix tree

### ISSUE THREAD

**Issue by abalage** [balabit/syslog-ng#384] opened 2015-02-16 11:15 UTC
Hello,

I have a quite big patterndb xml file. 
My problem is that upon using it / or testing it with "pdbtool test --validate /path/to/xml" I receive such messages.

Duplicate parser node in radix tree; type='1', name='.exit_code', value='41b3d595-eea8-4369-aeba-2b04cc7931c8'
Duplicate key in radix tree; key='deadlock detected, killing process;', value='7ea0095a-1cfe-4452-aaec-49f8cc5d5482'
Duplicate parser node in radix tree; type='1', name='.exit_code', value='7ea0095a-1cfe-4452-aaec-49f8cc5d5482'

I know what these errors mean so I have checked the xml file to see where the duplicates are. In fact the duplicate patterns can be found indeed however they do belong to different rulesets where the program pattern is also different.
- If I change only the name of the parser which is an optional setting according to the documentation the case is gone. 
- If I only copy the two affected rulesets into a separate xml file then it validates correctly without errors.

The generated xml (update-patterndb) file is version 4 while the sources are version 3.

Version:
syslog-ng --version
syslog-ng 3.6.2
Installer-Version: 3.6.2
Revision: 
Compile-Date: Jan  6 2015 23:05:04
Available-Modules: dbparser,cryptofuncs,afsql,afmongodb,pseudofile,system-source,linux-kmsg-format,afuser,affile,afstomp,afsocket-tls,basicfuncs,confgen,afsocket,graphite,syslogformat,afamqp,csvparser,sdjournal,afprog,afsocket-notls
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

Arch Linux if that does matter.

If you need the xml file then get in touch with me privately as it is not a public domain. (Balage)

**Comment by bazsi** [comment] 2015-02-16 14:13
-- 
Bazsi

On Mon, Feb 16, 2015 at 12:15 PM, abalage <notifications@github.com> wrote:

> Hello,
>
> I have a quite big patterndb xml file.
> My problem is that upon using it / or testing it with "pdbtool test
> --validate /path/to/xml" I receive such messages.
>
> Duplicate parser node in radix tree; type='1', name='.exit_code',
> value='41b3d595-eea8-4369-aeba-2b04cc7931c8'
> Duplicate key in radix tree; key='deadlock detected, killing process;',
> value='7ea0095a-1cfe-4452-aaec-49f8cc5d5482'
> Duplicate parser node in radix tree; type='1', name='.exit_code',
> value='7ea0095a-1cfe-4452-aaec-49f8cc5d5482'
>
> I know what these errors mean so I have checked the xml file to see where
> the duplicates are. In fact the duplicate patterns can be found indeed
> however they do belong to different rulesets where the program pattern is
> also different.
>
>    - If I change only the name of the parser which is an optional setting
>    according to the documentation the case is gone.
>    - If I only copy the two affected rulesets into a separate xml file
>    then it validates correctly without errors.
>
>
hmm.. different programs are inserted into a separate radix tree, so I
don't see how the duplicates should occur, unless the program is also the
same. If you can send me the XML in private, I would try to diagnose your
problem. My email is bazsi77@gmail.com.

Thanks.

**Comment by abalage** [comment] 2015-02-16 14:25
Thanks. I have already sent it to your mail address.

**Comment by bazsi** [comment] 2015-02-16 14:31
The issue is that you have an @ANYSTRING@ parser that catches all remaining
logs, this way you have two rules that could potentially match. In this
case, the order matters and the first one would be found.

On the other hand, if you omitted the @ANYSTRING@ parser, that match would
be shorter than the actual rule, causing the longer match to be preferred,
avoiding the conflict.

-- 
Bazsi

**Comment by abalage** [comment] 2015-02-16 14:43
Hm. I do not have @ANYSTRING@ in neither of the mentioned rulesets, except in the username but with a prefix.
If you meant <pattern>@ANYSTRING@</pattern> then those are only used in rulesets where the program name should be explicit enough.
Did I miss something?

**Comment by bazsi** [comment] 2015-02-16 16:24
Here's one of the offending rules which conflicts:

      <rule class='kernel' id='a49d840a-7722-49f2-afc0-53a33cc367ce'
provider='balabit'>
      <description>All other kernel-messages</description>
        <patterns>
          <pattern>@QSTRING:kernel.stamp:[]@ @ANYSTRING@</pattern>
        </patterns>
        <values>
        </values>
        <examples>
         <example>
          <test_message program='kernel'>[2867685.113438] Pid: 29244, comm:
searchd Not tainted 3.2.0-672-xcb #0</test_message>
         </example>
        </examples>
      </rule>

It conflicts with this one:

      <rule class='raid' id='25c26083-b5fd-437b-aa73-baf3ea7d2334'
provider='balabit'>
      <description>(Software-)RAID related messages</description>
        <patterns>
          <pattern>@QSTRING:kernel.stamp:[]@ md: @ANYSTRING@</pattern>
        </patterns>
        <values>
        </values>
        <examples>
         <example>
          <test_message program='kernel'>[217243.338531] md: using maximum
available idle IO bandwidth (but not more than 200000 KB/sec) for
data-check.</test_message>
         </example>
        </examples>
      </rule>

The program name is not in the <ruleset> pattern, but rather within the
normal part of the rule, in which case a parser and the string literal both
match, and both of them is a complete match (e.g. matches to the last
character). This is a conflict which cannot be decided any other way. If
you remove the @ANYSTRING@ then the 2nd rule becomes a partial match, which
means it is less preferred, resolving the conflict.





-- 
Bazsi

**Comment by faxm0dem** [comment] 2015-02-16 21:42
If you absolutely need both rules, you could cascade them using two different patterndb parsers. This is what we usually do at my organization: pass all messages through a very specific patterndb, then to another with more generic, "catchall" patterns if the first one didn't match.

**Comment by abalage** [comment] 2015-02-17 10:02
It's still not clear for me. I have no troubles with the two rules in that ruleset where the program name is 'kernel'. I have the expected behavior. 
But I have issues with the duplicates from the initial report.

rule id 41b3d595-eea8-4369-aeba-2b04cc7931c8
and
rule id 7ea0095a-1cfe-4452-aaec-49f8cc5d5482

If the cause of them is the conflict in rulesets belonging to 'kernel' then the error message is  confusing.

**Comment by bazsi** [comment] 2015-02-17 14:58
I have just submitted pr#386 which should resolve the conflicts in your file.

**Comment by bazsi** [comment] 2015-02-17 15:00
I mean pull request #386, if you can pls test the branch and report back if it indeed fixes your issue.

thanks.

**Comment by abalage** [comment] 2015-02-19 11:46
Duplicates have gone, though I have some conflicting rules, but anyway I will sort them out.
Thanks for the help.

**Closed** 2015-02-19 12:32 UTC
