### ISSUE TITLE
Riemann destination does not handle closing TCP connection very well

### ISSUE THREAD

**Issue by mmannerm** [balabit/syslog-ng#498] opened 2015-05-29 21:20 UTC
There is an issue in the underlying riemann_c_client that is used, that it does not check whether the TCP connection is alive or not: https://github.com/algernon/riemann-c-client/issues/9

This will result that if you have for example AWS ELB in front of riemann, which will issue TCP FIN after e.g. 60 seconds on no activity, the TCP connection dies, but syslog-ng does not realize it and keeps trying to send with old connection.

**Comment by algernon** [comment] 2015-06-01 07:25
The fix for this is [here](https://github.com/algernon/syslog-ng/commit/986404a56e01485be215490142090a3d3e1f4614). The patch needs some work, because ideally, the timeout would be configurable.

Also, `riemann-c-client` 1.8.0 will have a function to do the same thing. Nevertheless, syslog-ng should keep using direct `setsockopt()`, to keep the required `riemann-c-client` version lower.

**Comment by ihrwein** [comment] 2015-06-02 13:54
@algernon I've cherry-picked your commit and created the missing `timeout()` parameter. 

https://github.com/ihrwein/syslog-ng/commits/f/rimemann-timeout

The problem is, that Ubuntu 14.04 and probably most distros don't ship riemann-client 1.2 or above, so this code needs to branch on the library version.

@mmannerm Could you include your syslog-ng version and what OS you use?

**Comment by algernon** [comment] 2015-06-02 17:10
Hrm.... if you want, I can provide a clever hack that works with riemann-c-client 1.0+, and will continue working as long as the ABI remains the same. But it is ugly. Interested?

**Comment by mmannerm** [comment] 2015-06-02 18:35
Ubuntu 14.04 LTS w/ syslog-ng 3.5.3-1 installed via apt-get (syslog-ng, syslog-ng-core and syslog-ng-mod-riemann)

{code}
$ syslog-ng --version
syslog-ng 3.5.3
Installer-Version: 3.5.3
Revision: 3.5.3-1 [@9695e81] (Ubuntu/14.04)
Compile-Date: Dec 25 2013 23:13:11
{code}

**Comment by ihrwein** [comment] 2015-06-03 07:21
I hope it's nicer than the current workaround :) What would be your proposal?

**Comment by algernon** [comment] 2015-06-03 08:01
If you cast `riemann_client_t *` to an `int *`, you get a pointer to the file descriptor used underneath, because `int fd` is the first element of the struct.

So getting the FD becomes `int fd = *(int *)client`. This works for all versions of riemann-c-client, and will continue working for the lifetime of the 1.x series (and likely even beyond).

**Comment by ihrwein** [comment] 2015-06-03 09:18
@lbudai  any thoughts on this? We may keep the defines, but use them only to get the fd via this clever hack or the proper `riemann_client_get_fd()` call.

**Comment by algernon** [comment] 2015-06-03 09:52
I'd skip the defines altogether. They're far more noise than the hack itself, and they don't get you any real benefits over it, imo. A comment like "Replace this with `riemann_client_get_fd()` if/when bumping riemann-c-client dependency to 1.2+" would be more helpful than the defines.

**Comment by lbudai** [comment] 2015-06-03 10:56
Hmmm.... this hack is not so elegant :-)

What if we increase the min version for riemann-c-client... ?

**Comment by algernon** [comment] 2015-06-03 11:24
That'd be preferable, but Ubuntu for example has a very old version only. Mind you, if you want TLS support for the riemann destination, you will eventually need to bump the dependency to 1.6+. May aswell do that now...

**Comment by lbudai** [comment] 2015-06-03 11:26
sounds good to me...
@ihrwein  ?

**Comment by ihrwein** [comment] 2015-06-03 11:33
Ok, so the solution is (now):
* bump the min version requirement to `1.6`
* remove the `#if`s and use `riemann_client_get_fd()`
* create a new issue to implement TLS support in Riemann destination

**Closed** 2015-06-03 13:56 UTC
Labels: in progress
