### ISSUE TITLE
syslog-ng fails to start if a target cannot be resolved

### ISSUE THREAD

**Issue by ajf101** [balabit/syslog-ng#553] opened 2015-07-08 18:36 UTC
If any one of the hostnames given in network destinations are not resolvable, syslog-ng will not start.

This means that there is no logging occurring on the system at all, including local logging, and therefore there is no logging to say why syslog is not starting, leaving users at a loss.

It would seem much better that only the affected destination is disabled, and syslog-ng continues to run up with those destinations not in use, so some subset of system logging can still occur. syslog-ng should also then log to the logs that destination is unavailable due to error resolving hostname, allowing users to discover and resolve the issue more effectively.

**Comment by faxm0dem** [comment] 2015-07-08 19:05
This is a duplicate of #318

**Closed** 2015-07-08 22:14 UTC
