### ISSUE TITLE
Segfault in nv_registry_get_handle_flags

### ISSUE THREAD

**Issue by akunszt** [balabit/syslog-ng#1919] opened 2018-03-08 14:45 UTC
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision: 3.8.1-10
Module-Directory: /usr/lib/syslog-ng/3.8
Module-Path: /usr/lib/syslog-ng/3.8
Available-Modules: basicfuncs,disk-buffer,cryptofuncs,afuser,linux-kmsg-format,cef,afprog,kvformat,date,sdjournal,dbparser,pseudofile,confgen,syslogformat,affile,afsocket,csvparser,system-source
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```

## Platform

A docker image created from debian:stretch with the following Dockerfile.

```
FROM debian:stretch

RUN apt-get update && \
        apt-get -y --no-install-recommends upgrade && \
        apt-get -y --no-install-recommends install syslog-ng-core syslog-ng-mod-journal && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "/usr/sbin/syslog-ng", "-F" ]
```

## Debug bundle

There isn't syslog-ng-debun in this version of syslog-ng, yet.

# Issue

## Failure

```
(gdb) bt
#0  nv_registry_get_handle_flags (self=0x564a4cee51b0, handle=1290888120) at ../../lib/logmsg/nvtable.h:91
#1  log_msg_append_format_sdata (self=self@entry=0x564a4cf16010, result=result@entry=0x564a4cf106c0, seq_num=seq_num@entry=0) at ../../lib/logmsg/logmsg.c:858
#2  0x00007fdb70cb06e9 in log_writer_format_log (self=self@entry=0x564a4cf15830, lm=lm@entry=0x564a4cf16010, result=0x564a4cf106c0) at ../../lib/logwriter.c:923
#3  0x00007fdb70cb1346 in log_writer_write_message (self=self@entry=0x564a4cf15830, msg=0x564a4cf16010, path_options=path_options@entry=0x7fdb6c1f2970, write_error=write_error@entry=0x7fdb6c1f296c) at ../../lib/logwriter.c:1101
#4  0x00007fdb70cb1655 in log_writer_flush (self=0x564a4cf15830, flush_mode=LW_FLUSH_NORMAL) at ../../lib/logwriter.c:1205
#5  0x00007fdb70cb176a in log_writer_work_perform (s=0x564a4cf15830) at ../../lib/logwriter.c:185
#6  0x00007fdb70cb334d in _work (self=<optimized out>) at ../../lib/mainloop-io-worker.c:52
#7  0x00007fdb6f6adda7 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#8  0x00007fdb6f6ad073 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#9  0x00007fdb6f6afa6c in iv_main () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#10 0x00007fdb6f6adbf4 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#11 0x00007fdb6f6b06c8 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#12 0x00007fdb6f493494 in start_thread (arg=0x7fdb6c1f5700) at pthread_create.c:333
#13 0x00007fdb6f1d5aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

```

I use the 3.8 version on a Debian docker image, because in the balabit/syslog-ng:3.14.1 image the systemd-journal() source isn't working at all (I opened another ticket about that issue).

We faced this issue originally in our Kubernetes environment when we first enabled to use disk queue files. Without the disk queue file settings this works (but we need a disk queue). When I changed the source from systemd-journal() to a plain file() - for debug purposes - then it worked too. So I think the issue occurs only when the source is systemd-journal() AND disk queue is enabled.

## Steps to reproduce

1. Start a netcat to accept TCP connections (it's the GNU netcat, not the OpenBSD one).

`nc -l -p 1234`

2. Start syslog-ng with the following command line.

`docker run -it --rm -h "syslog-$RANDOM" -v ~/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf -v /tmp/dq:/var/lib/syslog-ng -v /var/log/journal:/var/log/journal -v /run/log:/run/log -v /run/systemd:/run/systemd -v /etc/machine-id:/etc/machine-id -e K8S_NODE=test debian_based_docker_image --no-caps -edv`

3. Confirm that the logs are shown on the netcat's output. Verify that the disk queue file is only 4096 byte long (aka it's empty).

4. Stop the netcat process with Ctrl-C or with this command.

`pkill nc`

5. Generate some test messages in the journald or just wait until the queue file grows.

`for((I=0;I<100;I++)); do logger "TEST MSG $I"; done`

5. Stop the syslog-ng with SIGTERM.

`pkill -TERM syslog-ng`

6. Start the syslog-ng again with the same docker command line.

7. Generate some test messages in the journald or just wait until the queue file grows.

`for((I=0;I<100;I++)); do logger "TEST MSG $I"; done`

8. Start the netcat process again.

`nc -l -p 1234`

9. Wait until the syslog-ng tries to reconnect.

10. Crash.

## Configuration

The crash happens with this configuration.

```
@version: 3.8

options {
        chain-hostnames( off );
        flush-lines( 0 );
        log-msg-size( 65536 );
        time-zone( "UTC" );
        ts-format( iso );
        use-dns( no );
        use-fqdn( no );
};

source s_docker_journald {
        systemd-journal( prefix( ".SDATA.journal." ) );
};

rewrite r_fakehost {
        set( "KISMACSKA38", value( ".SDATA.journal._HOSTNAME" ) );
};

destination d_relay {
        syslog(
                "172.17.0.1"
                transport( "tcp" )
                port( 1234 )
                log-fifo-size( 1000 )
                disk-buffer(
                        reliable( no )
                        disk-buf-size( 1073741824 )
                        mem-buf-length( 10000 )
                )
        );
};

log {
        source( s_docker_journald );
        rewrite( r_fakehost );
        destination( d_relay );
};

```

## Input and output logs (if possible)

There isn't anything in the debug logs, the last line is this:

```
[2018-03-08T14:32:31.578595] Syslog connection established; fd='15', server='AF_INET(172.17.0.1:1234)', local='AF_INET(0.0.0.0:0)'
```

**Comment by furiel** [comment] 2018-03-08 17:06
@akunszt this was fixed in https://github.com/balabit/syslog-ng/pull/1836. Can you try 3.14?

**Comment by furiel** [comment] 2018-03-08 17:09
Sorry, I missed the point that 3.14 does not work for you. You might try to backport that patch

**Comment by gaborznagy** [comment] 2018-03-09 10:13
@akunszt: as a temporary workaround you can invoke `threaded(no)` in global options.

**Comment by akunszt** [comment] 2018-03-09 11:50
@gaborznagy Thank you but it crashes with the same backtrace even if I add the `threaded( no )` to the global options.

I'll try to build a 3.14.1 from source as the fix mentioned by @furiel - thanks for the tip - is included in 3.14.1. I can't use the balabit/syslog-ng:3.14.1 Docker image nor the precompiled RPMs from @czanik repository because they are failing to read the local journald. I hope that this is caused by a configuration/build option and not a regression (balabit:syslog-ng:3.6 also fail to read the local journald while the docker image I built based on the Debian 3.8 package can do that).

**Comment by furiel** [comment] 2018-03-09 12:56
I just tried journald-source() and it works for me. I used this small configuration and docker run command. Maybe it helps:

```
$ cat syslog-ng-journald-test.conf 
@version: 3.14

log {
    source { stdin(); };
    source { systemd-journal(); };
    destination { file("/dev/stdout"); };
};
```

```
$ docker run -ti -v $HOME/syslog-ng-journald-test.conf:/etc/syslog-ng/syslog-ng.conf -v /var/log/journal:/var/log/journal -v /run/log:/run/log -v /run/systemd:/run/systemd balabit/syslog-ng:3.14.1
syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
Mar  9 06:21:43 f5ce128ffd09 systemd-journald[348]: Runtime journal (/run/log/journal/) is 8.0M, max 159.1M, 151.1M free.
Mar  9 06:21:43 f5ce128ffd09 kernel: random: get_random_bytes called from start_kernel+0x42/0x50d with crng_init=0
[...]
```

**Comment by akunszt** [comment] 2018-03-09 13:41
Thanks @furiel. I tried your config and command line and it didn't worked for me. It didn't write out anything on the stdout except the capability error message. It can read the logs from the STDIN, that part works. I tried with both a normal user and with sudo too. It's a Debian 9.3 with a recent docker:
```
$ docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:21 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:15:56 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
What's your docker version? OS?

**Comment by furiel** [comment] 2018-03-09 13:49
```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ cat /etc/issue
Ubuntu 16.04.4 LTS \n \l
```

Can you check if systemd/journald works inside the container, without syslog-ng involved? For example, can you `$ systemd-cat` inside the container, then read it back with `journalctl`?

**Comment by akunszt** [comment] 2018-03-09 15:32
The systemd-cat works. It connects to the /run/systemd/journal/stdout socket and I can see the message in the journal.

The syslog-ng first check for the /run/log/journal - which doesn't exists even on the host either - and then call an inotify_add_watch() on /var/log/journal which returns with 1, which looks good. The Debian version call inotify using /proc/self/FD where the FD points to /var/log/journal and the machine directory inside it. This is the difference I saw in the strace files, I don't know if it's relevant or not.
Debian packaged 3.8:
```
211   inotify_init1(IN_NONBLOCK|IN_CLOEXEC) = 11
211   open("/run/log/journal", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
211   open("/var/log/journal", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 12
211   fstat(12, {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
211   inotify_add_watch(11, "/proc/self/fd/12", IN_MODIFY|IN_ATTRIB|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_ONLYDIR) = 1
211   getdents(12, /* 3 entries */, 32768) = 104
211   open("/var/log/journal/c676251941774dc8b4205b2c51a024b4", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 19                                                                              
211   fstat(19, {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
211   inotify_add_watch(11, "/proc/self/fd/19", IN_MODIFY|IN_ATTRIB|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = 2
```

The balabit/syslog-ng:3.14.1:
```
96    inotify_init1(O_NONBLOCK|O_CLOEXEC) = 13
96    openat(AT_FDCWD, "/run/log/journal", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
96    openat(AT_FDCWD, "/var/log/journal", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 14
96    inotify_add_watch(13, "/var/log/journal", IN_MODIFY|IN_ATTRIB|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_ONLYDIR) = 1
```

**Comment by akunszt** [comment] 2018-03-09 16:20
The funny thing that your docker command works under Ubuntu 16.04.3 but not under Ubuntu 17.10, Debian 9.3 and CoreOS/ContainerLinux v1.9.3+coreos.0. In Ubuntu 16.04.3 the - default installation - uses only the /run/log/journal and the /var/log/journal is empty. The other distributions does the opposite.

**Comment by furiel** [comment] 2018-03-10 15:19
You are right: I tried with ubuntu 17.10, and the docker image did not work for me either by default.

I suspect the problem arises from different version of journald is used on the host than in the container. The container is built with the version available in jessie, which will not match with arbitrary host. If we want to be sure, we need a container that is based on the same distribution that is the host.

In the end I managed ubuntu 17.10 to work by doing this:
- Started with the dockerfile in https://github.com/balabit/syslog-ng-docker/blob/master/syslog-ng/Dockerfile
- Replaced the FROM to match ubuntu:artful
- Edited the syslog-ng repository from Debian_8.9 to xUbuntu_17.10 in the Dockerfile
- Unfortunately the default artful container did not ship journald, so I needed to install systemd-journal-remote inside the container.

And finally I needed to cross-map the journald volume from var to run: -v /var/log/journal:/run/log/journal
(I don't know how would I have catched this without your explanation above :))

If a started this crafted image, journalctl worked nicely: showing journald logs from the host, and also syslog-ng is working as expected.

**Comment by akunszt** [comment] 2018-03-12 10:06
Thanks @furiel. Based on your description I created a Debian based docker image (it's smaller than the Ubuntu one) which can read the journald messages. So I was able to test if 3.14.1 solves my original problem or not. The sad part that 3.14.1 also crashes with the same backtrace.
```
(gdb) bt
#0  nv_registry_get_handle_flags (self=0x55b08aba70d0, handle=2327514400) at ../../lib/logmsg/nvtable.h:86
#1  log_msg_append_format_sdata (self=self@entry=0x55b08abbf1a0, result=result@entry=0x55b08abd6b60, seq_num=seq_num@entry=0) at ../../lib/logmsg/logmsg.c:932
#2  0x00007f2fbd856691 in log_writer_format_log (self=self@entry=0x55b08abbe9c0, lm=lm@entry=0x55b08abbf1a0, result=0x55b08abd6b60) at ../../lib/logwriter.c:919
#3  0x00007f2fbd8572e6 in log_writer_write_message (self=self@entry=0x55b08abbe9c0, msg=msg@entry=0x55b08abbf1a0, path_options=path_options@entry=0x7f2fb6b8b950, write_error=write_error@entry=0x7f2fb6b8b948) at ../../lib/logwriter.c:1098
#4  0x00007f2fbd857670 in log_writer_flush (self=self@entry=0x55b08abbe9c0, flush_mode=flush_mode@entry=LW_FLUSH_NORMAL) at ../../lib/logwriter.c:1206
#5  0x00007f2fbd8577aa in log_writer_work_perform (s=0x55b08abbe9c0) at ../../lib/logwriter.c:184
#6  0x00007f2fbd85974d in _work (self=<optimized out>) at ../../lib/mainloop-io-worker.c:53
#7  0x00007f2fbc24d5e0 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#8  0x00007f2fbc24beef in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#9  0x00007f2fbc24c557 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#10 0x00007f2fbc24f8ae in iv_main () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#11 0x00007f2fbc24d403 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#12 0x00007f2fbc250c1c in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#13 0x00007f2fbc032494 in start_thread (arg=0x7f2fb6b8e700) at pthread_create.c:333
#14 0x00007f2fbbd74acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by gaborznagy** [comment] 2018-03-12 16:22
Hi @akunszt!

I reproduced the issue with your config without any docker image, seeing the same backtrace.
The occurrence was 1 out of 20 so far. How often do you face this issue?
We need to investigate this issue further.

**Comment by akunszt** [comment] 2018-03-13 07:12
Thanks @gaborznagy!

I didn't take notes but I can't recall a case when it didn't crashed in this scenario. So I can say it happens everytime.

**Comment by gaborznagy** [comment] 2018-03-19 16:22
Hi @akunszt!

I have made some small progress and narrowed the down the possible problems.
Reproduction steps (same config:  journal source, but no rewrite rule used):
  * syslog-ng started, it read ~7000 messages, network destination is not available
  * syslog-ng stopped (diskq saved)
  * start syslog-ng
  * generate 100 more messages with `logger`: `for((I=0;I<100;I++)); do logger "TEST MSG $I"; done`
    syslog-ng processed 101 messages (there were another system log as well)
  * open network destination, syslog-ng connects, starts sending data, then CRASH

I have watched the disk-queue during reproduction and saw that when the crash occurs we have a corrupted disk-queue (before opening the destination)!
```  
  gabornagy@gaborzbot:~/install/syslog-ng-OSE$ bin/dqtool info var/syslog-ng-00000.qf                                                             
  Inconsistent header data in disk-queue file, ignoring qout; filename='var/syslog-ng-00000.qf', qout_ofs='12094173', qdisk_length='7252'
  Disk-buffer state loaded; filename='var/syslog-ng-00000.qf', qout_length='64', qbacklog_length='0', qoverflow_length='0', qdisk_length='7252'
```

**Comment by akunszt** [comment] 2018-03-23 13:58
Thank you for your dedicated work on this case!

As you could reproduce the issue is there any information necessary from my side?

**Comment by Kokan** [comment] 2018-04-05 05:03
@akunszt 
I have created a PR that fixes a crash related to disk, I think it also fixes your issue.
The tricky part that it requires syslog-ng to first save the message into the disk buffer, and read it back from it. (Because the bug is when the messages is read back from the disk queue file.)

Would you give it a try ?

**Comment by akunszt** [comment] 2018-04-05 08:51
@Kokan 
Thank you very much. I can build and test it during the next week. I'll be back with the results.

**Comment by gaborznagy** [comment] 2018-06-01 08:54
Hello @akunszt!

We have a new PR for this issue, which I've tested and it is working. #2067

**Comment by akunszt** [comment] 2018-06-01 10:08
Thank you very much!

I can give it a try on next week and report back to you.

**Comment by akunszt** [comment] 2018-06-04 12:19
I applied the patches to the 3.14.1 version and it's working now! Thank you very much!

**Comment by Kokan** [comment] 2018-06-04 12:21
Thanks for checking this, it is going to be part of next release.

**Comment by Kokan** [comment] 2018-06-07 07:06
The #2067 has been merged.

**Closed by Kokan** 2018-06-07 07:06 UTC
Labels: bug
