### ISSUE TITLE
"syslog-ng -s" does not fail on wrong quotation marks.

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1293] opened 2016-12-28 20:20 UTC
# syslog-ng

Original report by gsamu@ca.ibm.com on Debian, verified by me on openSUSE.

## Version of syslog-ng

```
# syslog-ng -V
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision: 
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules: dbparser,afstomp,graphite,csvparser,afsocket,affile,cef,confgen,json-plugin,date,system-source,disk-buffer,kvformat,afamqp,pseudofile,cryptofuncs,basicfuncs,sdjournal,add-contextual-data,linux-kmsg-format,afmongodb,afuser,syslogformat,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```
But the original reporter had the same problem on syslog-ng 3.3.5 running on Debian.

## Platform

Debian and openSUSE

# Issue

## Failure

"syslog-ng -s" did not complain on the wrong quotation marks. We copy and pasted configuration example from https://pzolee.blogs.balabit.com/2014/01/measuring-log-collection-performance/ which has incorrect quotation marks around the file destination:
```
    # config_0: A very simple config with default values.
    # It receives messages from network and writes them into a file
    @version: 3.3
    source s_network { tcp(port(1514)); };
    destination d_local { file(“/var/log/syslog-ng.log”); };
    log { source(s_network); destination(d_local); };
```
No file was created. Debugging with "syslog-ng -Fvde" revealed that:
```
Incoming log entry; line='<38>2016-12-28T12:21:06 localhost prg00000[1234]: seq: 0000015279, thread: 0000, runid: 1482945661, stamp: 2016-12-28T12:21:06 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD' Error opening file for writing; filename='\xe2\x80\x9c/var/log/syslog-ng.log\xe2\x80\x9d', error='No such file or directory (2)'
```

## Steps to reproduce

Copy and paste configuration from the above URL and run syntax check"syslog-ng -s" on it. 

## Input and output logs (if possible)

Used loggen.

**Comment by bazsi** [comment] 2016-12-29 06:30
Well, these are utf8 quotation marks, which are simply recognized as mere
characters.

Since quotation is optional, those were added to the literal value.

So, its not a bug per se, but I understand that it may not be intuitive,
given those quotes do look like quotes.


On Dec 28, 2016 21:20, "czanik" <notifications@github.com> wrote:

syslog-ng

Original report by gsamu@ca.ibm.com on Debian, verified by me on openSUSE.
Version of syslog-ng

# syslog-ng -V
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision:
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules:
dbparser,afstomp,graphite,csvparser,afsocket,affile,cef,confgen,json-plugin,date,system-source,disk-buffer,kvformat,afamqp,pseudofile,cryptofuncs,basicfuncs,sdjournal,add-contextual-data,linux-kmsg-format,afmongodb,afuser,syslogformat,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off

But the original reporter had the same problem on syslog-ng 3.3.5 running
on Debian.
Platform

Debian and openSUSE
Issue Failure

"syslog-ng -s" did not complain on the wrong quotation marks. We copy and
pasted configuration example from https://pzolee.blogs.balabit.
com/2014/01/measuring-log-collection-performance/ which has incorrect
quotation marks around the file destination:

    # config_0: A very simple config with default values.
    # It receives messages from network and writes them into a file
    @version: 3.3
    source s_network { tcp(port(1514)); };
    destination d_local { file(“/var/log/syslog-ng.log”); };
    log { source(s_network); destination(d_local); };

No file was created. Debugging with "syslog-ng -Fvde" revealed that:

Incoming log entry; line='<38>2016-12-28T12:21:06 localhost
prg00000[1234]: seq: 0000015279, thread: 0000, runid: 1482945661,
stamp: 2016-12-28T12:21:06
PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD'
Error opening file for writing;
filename='\xe2\x80\x9c/var/log/syslog-ng.log\xe2\x80\x9d', error='No
such file or directory (2)'

Steps to reproduce

Copy and paste configuration from the above URL and run syntax
check"syslog-ng -s" on it.
Input and output logs (if possible)

Used loggen.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/issues/1293>, or mute the thread

**Comment by faxm0dem** [comment] 2016-12-29 20:53
I tend to agree with @baszi *but* I also think the parser would benefit from standardisation :

* make all strings the same (either quoted or unquoted)
* make all numbers unquoted 
* make all other things that look like strings like strings 

The reason I'm saying this is I have the impression there's no standard across all drivers be it scl native or Java modules

**Comment by bazsi** [comment] 2017-01-03 12:43
We could easily require quotation around strings, e.g. require quote
characters in the case:

tcp("1.2.3.4")

Now it is allowed to write:

tcp(1.2.3.4)

the error message would be something like:

Or:

source "s_all" {};

From these, I think the tcp() example is not a problem, requiring quotes
there is probably best practice. The second on the other hand would be more
problematic. Hmm, we could separate the two, e.g.
1) allow unquoted form but still allow quotes (source statement)
2) require quotation (e.g. IP addresses and hostnames)

It could even work with older versions (e.g. @version: 3.8 would yield
current behaviour), but still, some configurations would definitely need to
be changed.

Would this be worth it?



-- 
Bazsi

**Comment by faxm0dem** [comment] 2017-01-03 17:14
probable Not ^^

**Comment by bazsi** [comment] 2017-02-17 01:46
Closing this as NOTABUG.

**Closed by bazsi** 2017-02-17 01:46 UTC
