### ISSUE TITLE
segfault in 3.18.1+ latest master

### ISSUE THREAD

**Issue by soubhik-c** [balabit/syslog-ng#2466] opened 2018-12-14 10:07 UTC
# syslog-ng
   * Consistently getting a segfault with http and load-balancing in the worker. We are ingesting into elasticsearch using native http. 
   * This bug is being hit after removing batch-timeout which essentially was doing reinit to the destination frequently & leaking memory (related ticket #2462). 
   * With this change, reaping of connections went down drastically (from ~1600 to 41 times in 10 hrs) and I was hoping this race condition won't get hit.

source revision number: 
```
commit 82a7a012353143314d8482b7f249e56367a4da59 (origin/master, origin/HEAD, master)
Merge: 42789ba97 0701ca590
Author: László Várady <3130044+MrAnno@users.noreply.github.com>
Date:   Thu Dec 6 16:12:33 2018 +0100
```
  
## Version of syslog-ng

```
syslog-ng 3 (3.18.1)
Config version: 3.18
Installer-Version: 3.18.1
Revision: 
Compile-Date: Dec 12 2018 08:22:17
Module-Directory: /opt/syslog-ng-dbg/lib/syslog-ng
Module-Path: /opt/syslog-ng-dbg/lib/syslog-ng
Include-Path: /opt/syslog-ng-dbg/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,examples,graphite,hook-commands,http,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,mod-java,mod-python,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,xml
Enable-Debug: on
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

CentOS 7 (with ubuntu-bionic inside docker container) 

## Debug bundle
[syslog.debun.syslogng-1.2018-12-12_12-34.521.tar.gz](https://github.com/balabit/syslog-ng/files/2679422/syslog.debun.syslogng-1.2018-12-12_12-34.521.tar.gz)

# Issue
The process terminates after a segmentation fault when run over a prolonged period of time ~10 hrs.

## Failure

dmesg logs the following error.
```
[Wed Dec 12 17:37:49 2018] syslog-ng[19395]: segfault at 0 ip 00007fc35b520925 sp 00007fc304cb4b40 error 4
[Wed Dec 12 17:37:49 2018]  in libsyslog-ng-3.18.so.0.0.0[7fc35b4d1000+fc000]
[Wed Dec 12 17:37:49 2018]  in libsyslog-ng-3.18.so.0.0.0[7fc35b4d1000+fc000]
[Wed Dec 12 17:38:55 2018] syslog-ng[19366]: segfault at 0 ip 00007f486efda925 sp 00007f4815670b40 error 4
[Wed Dec 12 17:38:55 2018] syslog-ng[19179]: segfault at 0 ip 00007f486efda925 sp 00007f481b7f2bf0 error 4
[Wed Dec 12 17:38:55 2018] syslog-ng[19316]: segfault at 0 ip 00007f486efda925 sp 00007f481fffbbf0 error 4
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018] syslog-ng[19348]: segfault at 0 ip 00007f486efda925 sp 00007f481e7f8bf0 error 4
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018] syslog-ng[19178]: segfault at 0 ip 00007f486efda925 sp 00007f481d7f6b40 error 4
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018] syslog-ng[19623]: segfault at 0 ip 00007f486efda925 sp 00007f4816e73b40 error 4
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[18881]: segfault at 0 ip 00007f5a5495b925 sp 00007f5a03bafb40 error 4
[Wed Dec 12 17:39:46 2018] syslog-ng[19249]: segfault at 0 ip 00007f5a5495b925 sp 00007f5a023acb40 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19050]: segfault at 0 ip 00007f5a5495b925 sp 00007f59fd06cbf0 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19175]: segfault at 0 ip 00007f5a5495b925 sp 00007f59fc86bb40 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19376]: segfault at 0 ip 00007f5a5495b925 sp 00007f5a043b0b40 error 4
[Wed Dec 12 17:39:46 2018]  in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19048]: segfault at 0 ip 00007f5a5495b925 sp 00007f59fd86db40 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19144]: segfault at 51 ip 00007f5a5495b925 sp 00007f59fe06eb40 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19274]: segfault at 0 ip 00007f5a5495b925 sp 00007f5a053b2bf0 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018]  in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Thu Dec 13 00:11:54 2018] syslog-ng[31818]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd771fa1b40 error 4
[Thu Dec 13 00:11:54 2018] syslog-ng[32733]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd76cbf8b40 error 4
[Thu Dec 13 00:11:54 2018]  in libsyslog-ng-3.18.so.0.0.0[7fd7c3d04000+fc000]
[Thu Dec 13 00:11:54 2018] syslog-ng[32537]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd774fa7b40 error 4
[Thu Dec 13 00:11:54 2018] syslog-ng[32808]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd775fa9b40 error 4
[Thu Dec 13 00:11:54 2018]  in libsyslog-ng-3.18.so.0.0.0[7fd7c3d04000+fc000]
[Thu Dec 13 00:11:54 2018]  in libsyslog-ng-3.18.so.0.0.0[7fd7c3d04000+fc000]
[Thu Dec 13 00:11:54 2018] syslog-ng[32866]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd6b37fab40 error 4
[Thu Dec 13 00:11:54 2018]  in libsyslog-ng-3.18.so.0.0.0[7fd7c3d04000+fc000]
```

if I am applying the offset correctly, ```addr2line``` points me like below
```
xx@yy:/source# addr2line -e /opt/syslog-ng-dbg/lib/libsyslog-ng.so -Cfia 0x4F925                       
0x000000000004f925
log_threaded_dest_driver_queue
/source/lib/logthrdestdrv.c:884
xx@yy:/source# addr2line -e /opt/syslog-ng-dbg/lib/libsyslog-ng.so -Cfi 0x4F925                        
log_threaded_dest_driver_queue
/source/lib/logthrdestdrv.c:884
xx@yy:/source# addr2line -e /opt/syslog-ng-dbg/lib/libsyslog-ng.so  0x4F925                           
/source/lib/logthrdestdrv.c:884
```

AFAI understand, in the exception line marked with '>>>'.  ```dw->queue```  might point to an invalid address while the queue is being freed by the 'destination timeout, reaping' sequence and thus results into segv.

```
static void
log_threaded_dest_driver_queue(LogPipe *s, LogMessage *msg,
                               const LogPathOptions *path_options)
{
.....
  LogThreadedDestWorker *dw = _lookup_worker(self, msg);
.....
  >>> log_queue_push_tail(dw->queue, log_msg_ref(msg), path_options);  <<<
....
}
```

The reaping may reduce the queue refcount to zero ?
```
static void
affile_dd_reap_writer(AFFileDestDriver *self, AFFileDestWriter *dw)
{
  LogWriter *writer = (LogWriter *)dw->writer;

  main_loop_assert_main_thread();

  if (self->filename_is_a_template)
    {
      /* remove from hash table */
      g_hash_table_remove(self->writer_hash, dw->filename);
    }
  else
    {
      g_assert(dw == self->single_writer);
      self->single_writer = NULL;
    }

  LogQueue *queue = log_writer_get_queue(writer);
  log_pipe_deinit(&dw->super);
>>>>  log_dest_driver_release_queue(&self->super, queue);
  log_pipe_unref(&dw->super);
}
```
should we invoke ```log_queue_ref``` around ```dw->queue``` in order to avoid getting release inadvertently ? Please suggest .

## Steps to reproduce

1. start syslog-ng

2. With below configuration, spawn couple of containers and push 300k msgs/sec 200 bytes each log message and ingest it into elasticsearch. Observe when ES pushes back.

## Configuration

```
@version: 3.18
@include "scl.conf"

options { 
        use_dns(no); use_fqdn(no);
        owner("root"); group("adm"); perm(0640);
        chain_hostnames(off);
        bad_hostname("^gconfd$");
        keep_hostname(yes);
        create_dirs(yes);
        flush_lines(10);
        stats_freq (300);
        stats_level(1);
        stats-max-dynamics(5);
        time_reap (120);
        log_fifo_size (10000);
        time_reopen (10);
};



########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src {
       #https://tinyurl.com/qj6f983
       #system();
       internal();
};

source network1  { syslog(transport(udp) port(`SRC_PORT1`) log_fetch_limit(2000));};
source network2  { syslog(transport(udp) port(`SRC_PORT2`) log_fetch_limit(2000));};
source network3  { syslog(transport(udp) port(`SRC_PORT3`) log_fetch_limit(2000));};
source network4  { syslog(transport(udp) port(`SRC_PORT4`) log_fetch_limit(2000));};
source network5  { syslog(transport(udp) port(`SRC_PORT5`) log_fetch_limit(2000));};
source network6  { syslog(transport(udp) port(`SRC_PORT6`) log_fetch_limit(2000));};
source network7  { syslog(transport(udp) port(`SRC_PORT7`) log_fetch_limit(2000));};
source network8  { syslog(transport(udp) port(`SRC_PORT8`) log_fetch_limit(2000));};
source network9  { syslog(transport(udp) port(`SRC_PORT9`) log_fetch_limit(2000));};
source network10 { syslog(transport(udp) port(`SRC_PORT10`) log_fetch_limit(2000));};
source network11 { syslog(transport(udp) port(`SRC_PORT11`) log_fetch_limit(2000));};
source network12 { syslog(transport(udp) port(`SRC_PORT12`) log_fetch_limit(2000));};


########################
# Destinations
########################
# First some standard logfile

destination d_syslog { file("`SYSNG_CONTAINER_LOGPATH`/syslog-ng-`SRC_PORT1`.log"); };

# The root's console.
#
destination d_console { usertty("root"); };

# Virtual console.
#
#destination d_console_all { file(`tty10`); };

########################
# Filters
########################

filter f_syslog3 { not facility(auth, authpriv, mail);  };

parser pattern_db {
  db-parser(
    file("/etc/syslog-ng/patterndb.xml")
    drop-unmatched(yes)
  );
};
rewrite add_prog{set("Traffic", value("PROGRAM"));};


##### Elasticsearch destination

block destination elasticsearchhttp(server("localhost:9200") persistname("http-persist") ) {
  http(
      persist-name("`persistname`")
       url( "http://10.176.1.xx:9201/generator-latest/traffic/_bulk"
          ,"http://10.176.1.xx:9202/generator-latest/traffic/_bulk"
          ,"http://10.176.1.xx:9203/generator-latest/traffic/_bulk"
          ,"http://10.176.1.xx:9204/generator-latest/traffic/_bulk")
      timeout(120)
      method("POST")
      flush-lines(500)
      flush-bytes(512Kb)
      flush-timeout(100)
      workers(8)
      headers("Content-Type: application/x-ndjson")
      body-suffix("\n")
      body('{ "index":{} }
           $(format-json --scope nv_pairs --exclude DATE --key ISODATE @timestamp=${ISODATE})')
 );
};

destination http1  { elasticsearchhttp(server("10.176.5.xxx:9201") persistname("http-persist-`SRC_PORT1`") );  };
destination http2  { elasticsearchhttp(server("10.176.5.xxx:9202") persistname("http-persist-`SRC_PORT2`") );  };
destination http3  { elasticsearchhttp(server("10.176.5.xxx:9203") persistname("http-persist-`SRC_PORT3`") );  };
destination http4  { elasticsearchhttp(server("10.176.5.xxx:9204") persistname("http-persist-`SRC_PORT4`") );  };
destination http5  { elasticsearchhttp(server("10.176.5.xxx:9201") persistname("http-persist-`SRC_PORT5`") );  };
destination http6  { elasticsearchhttp(server("10.176.5.xxx:9202") persistname("http-persist-`SRC_PORT6`") );  };
destination http7  { elasticsearchhttp(server("10.176.5.xxx:9203") persistname("http-persist-`SRC_PORT7`") );  };
destination http8  { elasticsearchhttp(server("10.176.5.xxx:9204") persistname("http-persist-`SRC_PORT8`") );  };
destination http9  { elasticsearchhttp(server("10.176.5.xxx:9201") persistname("http-persist-`SRC_PORT9`") );  };
destination http10 { elasticsearchhttp(server("10.176.5.xxx:9202") persistname("http-persist-`SRC_PORT10`") );  };
destination http11 { elasticsearchhttp(server("10.176.5.xxx:9203") persistname("http-persist-`SRC_PORT11`") );  };
destination http12 { elasticsearchhttp(server("10.176.5.xxx:9204") persistname("http-persist-`SRC_PORT12`") );  };


########################
# Log paths
########################


log { source(s_src); filter(f_syslog3); destination(d_syslog); flags(final); };

log { source(network1); rewrite(add_prog); parser(pattern_db); destination(http1); flags(final); };
log { source(network2); rewrite(add_prog); parser(pattern_db); destination(http2); flags(final); };
log { source(network3); rewrite(add_prog); parser(pattern_db); destination(http3); flags(final); };
log { source(network4); rewrite(add_prog); parser(pattern_db); destination(http4); flags(final); };
log { source(network5); rewrite(add_prog); parser(pattern_db); destination(http5); flags(final); };
log { source(network6); rewrite(add_prog); parser(pattern_db); destination(http6); flags(final); };
log { source(network7); rewrite(add_prog); parser(pattern_db); destination(http7); flags(final); };
log { source(network8); rewrite(add_prog); parser(pattern_db); destination(http8); flags(final); };
log { source(network9); rewrite(add_prog); parser(pattern_db); destination(http9); flags(final); };
log { source(network10); rewrite(add_prog); parser(pattern_db); destination(http10); flags(final); };
log { source(network11); rewrite(add_prog); parser(pattern_db); destination(http11); flags(final); };
log { source(network12); rewrite(add_prog); parser(pattern_db); destination(http12); flags(final); };


```

(or gist URL)

**Comment by soubhik-c** [comment] 2019-01-07 08:13
@bazsi Hi, missed updating the project and milestone details.. could you please triage this bug

**Comment by alltilla** [comment] 2019-01-21 13:14
Hi Soubhik,

Sorry for the late answer.

I tried to reproduce both this issue and #2462, but I did not succeed.
Although, I found an interesting part in your config:

The `server` argument of your `elasticsearchhttp` block is not used anywhere. The logs are sent to http://10.176.1.xx:9201, ..2, ..3, ..4 every time. So you have seemingly different destinations, which are all the same. This might cause some hiccups. I suggest to modify the config something like this:

```
block destination elasticsearchhttp(server("localhost") persistname("http-persist") ) {
  http(
      persist-name("`persistname`")
       url("`server`:9201/generator-latest/traffic/_bulk"
          ,"`server`:9202/generator-latest/traffic/_bulk"
          ,"`server`:9203/generator-latest/traffic/_bulk"
          ,"`server`:9204/generator-latest/traffic/_bulk")
...
 );
```
With this, probably you will only need 3 destinations, as you would like to send to 3 different IP's 4 different port each. Also you should not set the port in the log path this way, because it will be set by the block, only the IP is needed.

Also, could you kindly tell where are these values set? `SRC_PORT1`, ...
It would be great, if you could send the config, in a way, I can use it for reproduction "out-of-the-box".

Regarding the investigation between `log_threaded_dest_driver_queue()` and `affile_dd_reap_writer()`, I think those two are not connected, because the `file` destination is not using the `threaded destination driver`, so they do not operate on the same queue. Although the problem might only occur, when both are present. Can you kindly try to reproduce the problem with disabling the file destination?

Commenting out the related log path is enough:
`#log { source(s_src); filter(f_syslog3); destination(d_syslog); flags(final); };`

Thank you very much!

Best regards,
Attila

**Comment by alltilla** [comment] 2019-01-23 14:38
Hi Soubhik,

Thank you for your kind support!

Could you kindly tell a little more about the following? "Observe when ES pushes back." Does it send 4XX or 5XX errorcode back, or just slowing down in processing, maybe something else? Knowing this could help a lot in reproducing, or finding the issue.

Regarding the invalid variable, I suppose it is the queue, but I cannot say for sure yet.

By the way there is an elasticsearch destination implementation in progress, tracked by #2509. It is based on http destination, like in this PR. Once it is merged, you could give that a try :)

Best regards,
Attila

**Comment by soubhik-c** [comment] 2019-01-23 16:35
I don't remember the error code but that will be ESRejectException i.e. queue_size being momentarily full on the other end. No other exception is observed.

> Regarding the invalid variable, I suppose it is the queue, but I cannot say for sure yet.

Ok.

So, what is the difference between current http native with load-balancing and the #2509 ? AFAI could gather its index and type information is outside the server url list. Strictly speaking, current impl with absolute url is more desirable for us because we are having one index per elastic host (to avoid portion of the bulk message redistributed outside the host once it reaches on the coordinator es node i.e. single hop). For example:
given following index definition
```
ES Host1 -> h1-index1
ES Host2 -> h2-index2
```
we could generate a server url like below.
```
elasticsearchdestination(
   server("http://h1:9601/h1-index1/x/_bulk" "http://h2:9602/h2-index/x/_bulk" )
)
```
This gives a straight up gain in performance by ~30% and provides much more stability to ingestion (very few ESRejects). However, this bug is reported without such bias i.e. simply ``h1:9061/index1/x/_bulk``

Also, I would like either this or the other bulk request api to have an option for "just look for status 200 in the bulk response header" and close the response stream without reading the full response. This gives a big gain in n/w bandwidth consumption & really helps sending more log messages to the destination. 
I did that in java-plugin and with connection pooling actually beats http native impl primarily because of this apart from more parallelism.
Another similar product rs*(not want to name it :)) performs better compared to this because of same optimization as one of the reason.

Thanks
Soubhik

**Comment by alltilla** [comment] 2019-01-24 15:28
Hi Soubhik,

I think we found the cause of the segfault, see #2512.
It happens with any threaded destination (http in our case) after 2^32 number of log messages. If you are building syslog-ng locally, you can cherry-pick that commit to use http-destination again.

Best regards,
Attila

**Comment by soubhik-c** [comment] 2019-01-24 17:02
awesome. I should have looked at it more closely... thanks a lot... will cherry pick and try sometime next week...

**Closed** 2019-01-25 09:02 UTC
Labels: bug

**Comment by furiel** [comment] 2019-01-25 17:24
@soubhik-c just one note, the java based elasticsearch in 3.18 does not work too well in terms of message loss, when elasticsearch drops the messages.

The elasticsearch2 with client-mode(http) is just fixed recently in https://github.com/balabit/syslog-ng/pull/2478. I suggest you update a relatively recent checkout. The older elasticsearch driver, or elasticsearch2 with non-http client mode are still affected.

When comparing the performance of the http destination and the java-http destination, it would worth taking the message loss into account: how many of the generated messages actually stored in elasticsearch. The http destination, and post #2478 the java-http destination too try to save the batch: in case of failure, after a `time-reopen` seconds of disconnect, the whole batch will be retried (`retries` number of times). Pre #2478, in case of batch failure, all messages except the last one that triggers the flush is lost, only the last one is saved into the next batch.
