### ISSUE TITLE
latest on Macos: compile issues

### ISSUE THREAD

**Issue by juju4** [balabit/syslog-ng#173] opened 2014-07-26 03:42 UTC
Hello,

I'm trying to update syslog-ng for macports on Macos (10.9.4)
A patch is referenced in old bugzilla https://bugzilla.balabit.com/show_bug.cgi?id=155
so I fit it to current configure.ac in 3.5.5 but I fall on another issue

```
  CC       tests/loggen/loggen.o
tests/loggen/loggen.c:911:80: warning: format specifies type 'long' but the argument has type 'int' [-Wformat]
    (double) sum_count * USEC_PER_SEC / diff_usec, sum_count, sum_time.tv_sec, sum_time.tv_usec / 1000, raw_message_length,
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~
  CC       syslog-ng/main.o
1 warning generated.
  CC       syslog-ng/syslog-ng-ctl.o
  AR       libtest/libsyslog-ng-test.a
syslog-ng/syslog-ng-ctl.c:98:60: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
      if ((len = read(control_socket, buff, BUFF_LEN - 1)) < 0)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
  CCLD     lib/libsyslog-ng.la
1 warning generated.
  CCLD     tests/loggen/loggen
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
duplicate symbol _last_parser in:
    lib/.libs/lib_libsyslog_ng_la-cfg-grammar.o
    lib/parser/.libs/lib_libsyslog_ng_la-parser-expr-grammar.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:3682: recipe for target 'lib/libsyslog-ng.la' failed
```

outcome also presented here https://github.com/Homebrew/homebrew/issues/22030

outside of *.y there are
```
extern LogParser *last_parser;
```
in modules/dbparser and modules/json.
var is used but not declared in modules/syslogformat and modules/csvparser so it could be that
it's only present as extern in one header lib/cfg-grammar.h

A possible explanation:
http://samwho.co.uk/blog/2013/12/08/duplicate-symbol-what/

**Comment by gregory094** [comment] 2015-02-04 11:36
I'm currently working on the solution of creating Brew Formula and updating MacPorts port file in order to make syslog-ng easy to install on MacOSX.  I'll post the commit ID-s of my collaboration to pkgs here.

**Comment by juju4** [comment] 2015-02-07 01:30
Thanks Gregory. hadn't time to dig more. If you can, great!

**Comment by gregory094** [comment] 2015-02-07 13:26
I've solved the issue you've mentioned. I'll push the fix to a branch on Monday. Please, compile it on your system and report me if any issues happened. I am planning to write a short guide about the tools needed for the proper installation.  There are some differences in Apple developer tools to GNU ones. Keep in touch!

**Comment by gregory094** [comment] 2015-02-11 15:58
I've just created a branch for MacOSX support called '3.5/f/macosx'. You can compile from there. It is tested on 10.9 and 10.10. 
Temporally you need to add __sun define when making. You can do that this way: 'make CFLAGS=-D__sun'. This issue will be corrected soon. I'm planning to write a short description about the process of installing on MacOSX.  Use 'bison' from brew package instead of the default (provided by Apple).  You can do that this way: 'export PATH=/usr/local/opt/bison/bin:$PATH'.

**Comment by juju4** [comment] 2015-04-05 23:49
Hello Gregory,

Sorry for the delay. Not found your macosx branch but gave a try to latest devel/commit and it seems to get better. Not full compile but.

Once I solve new dependencies issues, I arrive at the following error
```
2 warnings generated.
  CC       lib/lib_libsyslog_ng_la-logmpx.lo
  CC       lib/lib_libsyslog_ng_la-logmsg.lo
  CC       lib/lib_libsyslog_ng_la-logpipe.lo
lib/logmsg.c:1678:16: error: only weak aliases are supported on darwin
__attribute__((alias("log_msg_get_value")));
               ^
lib/logmsg.c:1682:16: error: only weak aliases are supported on darwin
__attribute__((alias("log_msg_get_value_by_name")));
               ^
2 errors generated.
  CC       lib/lib_libsyslog_ng_la-logqueue.lo
Makefile:7164: recipe for target 'lib/lib_libsyslog_ng_la-logmsg.lo' failed
gmake[2]: *** [lib/lib_libsyslog_ng_la-logmsg.lo] Error 
```
I'm doing a macports Port.
same error with CFLAGS=-D__sun

**Comment by gregory094** [comment] 2015-04-06 09:09
Hello!
Np. I'm working on integrating my macosx branch to syslog-ng (3.7, 3.6) it just takes time to solve the problems. There is only one barrier left for the integration that is ivykis depencency. If my solution can be accepted to their repo all my branches can be merged.
Till then: [here](https://github.com/gregory094/syslog-ng/tree/3.6/f/macosx) you can find my branch.  Try that, I hope it will work!

Could you give me some details about your OS? MacOSX 10.X?

**Comment by juju4** [comment] 2015-04-06 22:15
I gave a try to yours and it fails on man page

```
:info:build modules/dbparser/patterndb.c:565:8: note: place parentheses around the '&&' expression to silence this warning
:info:build   CC       modules/dbparser/modules_dbparser_libsyslog_ng_patterndb_la-timerwheel.lo
:info:build               && pdb_rule_check_rate_limit(self, db, action, msg, buffer)))
:info:build               ^   
:info:build 1 warning generated.
:info:build   CC       modules/dbparser/modules_dbparser_libsyslog_ng_patterndb_la-patternize.lo
:info:build   GEN      doc/man/syslog-ng.8
:info:build   GEN      doc/man/syslog-ng.conf.5
:info:build warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
:info:build cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
:info:build warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
:info:build cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
:info:build Makefile:11366: recipe for target 'doc/man/syslog-ng.conf.5' failed
:info:build gmake[2]: *** [doc/man/syslog-ng.conf.5] Error 4
```

I have 10.10.2 and you can see my ports update here
https://trac.macports.org/ticket/43231

**Comment by gregory094** [comment] 2015-04-06 23:32
Yes, generation of manages hasn't been merged to macosx support yet. You install docbook-xsl using homebrew and specify XSL_STYLESHEET variable to point to your Cellar docbook-xsl installation.
example: `make XSL_STYLESHEET=/usr/local/Cellar/....../docbook.xsl` 
This will work! (The problem is that this path is burnt into to the makefile. I've already fixed that in #431 and #440.) 
My branch hopefully will be merged slowly to the master (after some polishment) and we will have an "out-of-the-box" install method for macosx.

**Comment by juju4** [comment] 2015-04-07 00:59
yeah. easy. add to my Portfile. build fines. install/destroot fails while it looks for doc/examples/header. Will look into it later.
Thanks a lot for the help!

**Comment by lbudai** [comment] 2015-04-14 07:34
Hmmm... the alias problem is a new one (started to using those aliases in #426  ).

**Comment by gregory094** [comment] 2015-06-08 10:27
Any news?

**Comment by ihrwein** [comment] 2015-12-14 11:38
@juju4 You may want to try this branch: https://github.com/gregory094/syslog-ng/tree/3.6/f/macosx

**Comment by pzoleex** [comment] 2016-09-02 11:14
Closing due to inactivity

**Closed by pzoleex** 2016-09-02 11:14 UTC
Labels: blocked, bug
