### ISSUE TITLE
mongoc does not compile on SLES 11 i586

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#940] opened 2016-02-19 11:18 UTC
It compiles fine on AMD64, and also on more recent i586 platforms, but compilation of mongoc fails on SLES 11 i586. The error message is:

```
[   90s]   CC       src/mongoc/libmongoc_priv_la-mongoc-host-list.lo
[   91s]   CC       src/mongoc/libmongoc_priv_la-mongoc-init.lo
[   91s] src/mongoc/mongoc-client.c: In function 'mongoc_client_default_stream_initiator':
[   91s] src/mongoc/mongoc-client.c:351: error: unable to find a register to spill in class 'GENERAL_REGS'
[   91s] src/mongoc/mongoc-client.c:351: error: this is the insn:
[   91s] (insn:HI 151 150 152 16 src/mongoc/mongoc-counters.defs:64 (parallel [
[   91s]             (set (reg:DI 132)
[   91s]                 (mem/v:DI (plus:SI (reg:SI 129)
[   91s]                         (reg/f:SI 71 [ D.22808 ])) [-1 S8 A32]))
[   91s]             (set (mem/v:DI (plus:SI (reg:SI 129)
[   91s]                         (reg/f:SI 71 [ D.22808 ])) [-1 S8 A32])
[   91s]                 (unspec_volatile:DI [
[   91s]                         (mem/v:DI (plus:SI (reg:SI 129)
[   91s]                                 (reg/f:SI 71 [ D.22808 ])) [-1 S8 A32])
[   91s]                         (reg:DI 132)
[   91s]                         (reg:SI 133)
[   91s]                         (reg:SI 134)
[   91s]                     ] 10))
[   91s]             (set (reg:CCZ 17 flags)
[   91s]                 (compare:CCZ (unspec_volatile:DI [
[   91s]                             (mem/v:DI (plus:SI (reg:SI 129)
[   91s]                                     (reg/f:SI 71 [ D.22808 ])) [-1 S8 A32])
[   91s]                             (reg:DI 132)
[   91s]                             (reg:SI 133)
[   91s]                             (reg:SI 134)
[   91s]                         ] 11)
[   91s]                     (reg:DI 132)))
[   91s]         ]) 1266 {*sync_double_compare_and_swap_ccdi_pic} (expr_list:REG_DEAD (reg:SI 134)
[   91s]         (expr_list:REG_DEAD (reg:SI 133)
[   91s]             (nil))))
[   91s] src/mongoc/mongoc-client.c:351: confused by earlier errors, bailing out
[   91s] make[2]: *** [src/mongoc/libmongoc_priv_la-mongoc-client.lo] Error 1
[   91s] make[2]: *** Waiting for unfinished jobs....
[   91s] src/mongoc/mongoc-cluster.c: In function 'mongoc_cluster_sendv_to_server':
[   91s] src/mongoc/mongoc-cluster.c:2362: error: unable to find a register to spill in class 'GENERAL_REGS'
[   91s] src/mongoc/mongoc-cluster.c:2362: error: this is the insn:
[   91s] (insn:HI 319 318 320 36 src/mongoc/mongoc-counters.defs:18 (parallel [
[   91s]             (set (reg:DI 207)
[   91s]                 (mem/v:DI (plus:SI (reg:SI 204)
[   91s]                         (reg/f:SI 91 [ D.13403 ])) [-1 S8 A32]))
[   91s]             (set (mem/v:DI (plus:SI (reg:SI 204)
[   91s]                         (reg/f:SI 91 [ D.13403 ])) [-1 S8 A32])
[   91s]                 (unspec_volatile:DI [
[   91s]                         (mem/v:DI (plus:SI (reg:SI 204)
[   91s]                                 (reg/f:SI 91 [ D.13403 ])) [-1 S8 A32])
[   91s]                         (reg:DI 207)
[   91s]                         (reg:SI 208)
[   91s]                         (reg:SI 209)
[   91s]                     ] 10))
[   91s]             (set (reg:CCZ 17 flags)
[   91s]                 (compare:CCZ (unspec_volatile:DI [
[   91s]                             (mem/v:DI (plus:SI (reg:SI 204)
[   91s]                                     (reg/f:SI 91 [ D.13403 ])) [-1 S8 A32])
[   91s]                             (reg:DI 207)
[   91s]                             (reg:SI 208)
[   91s]                             (reg:SI 209)
[   91s]                         ] 11)
[   91s]                     (reg:DI 207)))
[   91s]         ]) 1266 {*sync_double_compare_and_swap_ccdi_pic} (expr_list:REG_DEAD (reg:SI 209)
[   91s]         (expr_list:REG_DEAD (reg:SI 208)
[   91s]             (nil))))
[   91s] src/mongoc/mongoc-cluster.c:2362: confused by earlier errors, bailing out
[   91s] make[2]: *** [src/mongoc/libmongoc_priv_la-mongoc-cluster.lo] Error 1
[   91s] make[2]: Leaving directory `/usr/src/packages/BUILD/syslog-ng-3.8.0alpha0/modules/afmongodb/mongo-c-driver'
[   91s] make[1]: *** [all-recursive] Error 1
[   91s] make[1]: Leaving directory `/usr/src/packages/BUILD/syslog-ng-3.8.0alpha0/modules/afmongodb/mongo-c-driver'
[   91s] make: *** [modules/afmongodb/mongo-c-driver/src/libmongoc-1.0.la] Error 2
```

**Comment by bkil-syslogng** [comment] 2016-02-19 11:30
@czanik Could you please try it with the newest `mongo-c-driver`? I guess you should add `branch = master` in `.gitmodules` and do a full `autogen.sh` & recompile.

**Comment by bkil-syslogng** [comment] 2016-02-19 11:38
@czanik If `mongo-c-driver/master` still has this issue, we can open an issue and/or PR upstream. If it fixes this issue and we can see no regression, we will update our module to either a newer branch, a tag or `master`.

**Comment by czanik** [comment] 2016-02-19 12:32
It fails at the same place. Not tested yet, but expect the RHEL6 build fail as well, as it uses the same old tool chain.

**Comment by bkil-syslogng** [comment] 2016-02-19 13:00
I found a `gcc` fix for this problem:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=16185#c17

Could you please open the same issue upstream and link it here? I guess it's enough to copy paste your provided information, because autogen & configure & make should fail in the same way without syslog-ng. If they reject the issue, we may consider looking into a proposed PR for them if somebody has time.
https://github.com/mongodb/mongo-c-driver#bugs--feature-requests

**Comment by MrAnno** [comment] 2017-12-01 13:27
Closing this due to inactivity.

**Closed by MrAnno** 2017-12-01 13:27 UTC
Labels: enhancement
