### ISSUE TITLE
The log would be lost

### ISSUE THREAD

**Issue by JoyChou93** [balabit/syslog-ng#1859] opened 2018-01-24 04:06 UTC
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3.2.5
Installer-Version: 3.2.5
Revision: ssh+git://bazsi@git.balabit//var/scm/git/syslog-ng/syslog-ng-ose--mainline--3.2#master#9d4bea28198bd731df1a61e980a2af5b88d81116
Compile-Date: Jul 25 2014 15:20:50
Enable-Threads: on
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-Sun-STREAMS: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-SSL: off
Enable-SQL: on
Enable-Linux-Caps: off
Enable-Pcre: on
Enable-Pacct: off
```

## Platform

centos 6.5

# Issue

## Failure

The log would be lost.

Normality, tcp connect should be 
```
$ sudo netstat -anop | grep syslog-ng
tcp        0      0 127.0.0.1:514               0.0.0.0:*                   LISTEN      23422/syslog-ng     off (0.00/0/0)
unix  2      [ ACC ]     STREAM     LISTENING     258045138 23422/syslog-ng     /var/lib/syslog-ng/syslog-ng.ctl
```

But the tcp connect :
```
$ sudo netstat -anop | grep syslog-ng
tcp        0      0 127.0.0.1:514               0.0.0.0:*                   LISTEN      29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:12576             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:14325             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:12848             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:14358             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:11482             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:23937             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:12651             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:14348             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:12336             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
tcp        0      0 127.0.0.1:514               127.0.0.1:11796             ESTABLISHED 29345/syslog-ng     off (0.00/0/0)
unix  2      [ ACC ]     STREAM     LISTENING     736481989 29345/syslog-ng     /var/lib/syslog-ng/syslog-ng.ctl
```

**Comment by Kokan** [comment] 2018-01-24 05:05
Hello,

Could you please elaborate' on how log loss is possible because of those netstat outputs ?

**Comment by JoyChou93** [comment] 2018-01-24 05:24
This is a matter of things, I test on a machine is also centos 6.5, will not lose the log, syslog-ng version is the same, its netstat state is not establishing a connection, so I guess so. But some machines will lose the log.

**Comment by JoyChou93** [comment] 2018-01-24 05:44
How should I debug the issue? Thanks.

**Comment by Kokan** [comment] 2018-01-24 05:54
I still do not quite understood your issue.

Could you please describe your setup, syslog-ng configuration, etc ... ?
You could also run the `https://raw.githubusercontent.com/balabit/syslog-ng/master/contrib/syslog-ng-debun` on your computer where syslog-ng is executed, with `syslog-ng-debug -R [syslog-ng install dir] -r` and share somewhere the created `tgz` file.

Note: the syslog-ng install dir is `/usr/local/` in case of `/usr/local/sbin/syslog-ng`, so the path without `/sbin/syslog-ng`.

But in the end my intuition tells me that this is a network issue rather then a syslog-ng.

**Comment by JoyChou93** [comment] 2018-01-24 06:30
There may be a network problem because there is a lot of nginx requests for the server where the log is lost, and the number of nginx requests for other servers that do not lose the log is relatively less.

**Comment by Kokan** [comment] 2018-01-24 06:40
Would it be possible for you to first verify if it is a network or syslog-ng issue ?
If it is turned out to be rather a syslog-ng issue, then please re-open it with a details of your findings. (Hopefully a way to reproduce it.)
I am closing this issue, because there is no indication currently that the message loss is because of syslo-ng.

**Closed by Kokan** 2018-01-24 06:40 UTC

**Comment by JoyChou93** [comment] 2018-01-25 07:56
I have found the reason. 

When i use the `internal()`, I found the msg as follows:

```
syslog-ng[16834]: Number of allowed concurrent connections reached, rejecting connection; client='AF_INET( X.X.X.X:48236)', local='AF_INET(0.0.0.0:514)', max='10'
```
so, adding the connection numbers solved the problem.
