### ISSUE TITLE
syslog-ng is stuck in an infinite loop of setsockopt() returning ENOTSOCK

### ISSUE THREAD

**Issue by keytoaster** [balabit/syslog-ng#670] opened 2015-09-03 11:27 UTC
Every once in a while (sometimes after hours, sometimes after months) syslog-ng gets stuck in an infinite loop, causing a high load. Attaching strace to the syslog-ng process shows me this:

```
# strace -p 14103
epoll_wait(3, {{EPOLLIN, {u32=10036472, u64=10036472}}}, 7, 132431) = 1
read(6, "\1\0\0\0\0\0\0\0", 8)          = 8
fcntl(14, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(14, F_GETFL)                      = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
setsockopt(14, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
clock_gettime(CLOCK_MONOTONIC, {9406481, 845868688}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 14, {EPOLLIN, {u32=10230848, u64=10230848}}) = 0
epoll_wait(3, {{EPOLLIN|EPOLLERR, {u32=10230848, u64=10230848}}}, 8, 132430) = 1
epoll_ctl(3, EPOLL_CTL_DEL, 14, 720068431c50) = 0
write(17, "\1\0\0\0\0\0\0\0", 8)        = 8
futex(0x99a2e0, FUTEX_WAKE_PRIVATE, 1)  = 1
clock_gettime(CLOCK_MONOTONIC, {9406481, 846850457}) = 0
epoll_wait(3, {{EPOLLIN, {u32=10036472, u64=10036472}}}, 7, 132429) = 1
read(6, "\1\0\0\0\0\0\0\0", 8)          = 8
fcntl(14, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(14, F_GETFL)                      = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
setsockopt(14, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
clock_gettime(CLOCK_MONOTONIC, {9406481, 847992972}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 14, {EPOLLIN, {u32=10230848, u64=10230848}}) = 0
epoll_wait(3, {{EPOLLIN|EPOLLERR, {u32=10230848, u64=10230848}}}, 8, 132428) = 1
epoll_ctl(3, EPOLL_CTL_DEL, 14, 720068431c50) = 0
write(17, "\1\0\0\0\0\0\0\0", 8)        = 8
futex(0x99a2e0, FUTEX_WAKE_PRIVATE, 1)  = 1
clock_gettime(CLOCK_MONOTONIC, {9406481, 849180866}) = 0
epoll_wait(3, {{EPOLLIN, {u32=10036472, u64=10036472}}}, 7, 132427) = 1
read(6, "\1\0\0\0\0\0\0\0", 8)          = 8
fcntl(14, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(14, F_GETFL)                      = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
setsockopt(14, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
clock_gettime(CLOCK_MONOTONIC, {9406481, 850060111}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 14, {EPOLLIN, {u32=10230848, u64=10230848}}) = 0
epoll_wait(3, {{EPOLLIN|EPOLLERR, {u32=10230848, u64=10230848}}}, 8, 132426) = 1
epoll_ctl(3, EPOLL_CTL_DEL, 14, 720068431c50) = 0
write(17, "\1\0\0\0\0\0\0\0", 8)        = 8
futex(0x99a2e0, FUTEX_WAKE_PRIVATE, 1)  = 1
clock_gettime(CLOCK_MONOTONIC, {9406481, 851036900}) = 0
epoll_wait(3, {{EPOLLIN, {u32=10036472, u64=10036472}}}, 7, 132425) = 1
```

Interestingly, the file descriptor used by setsockopt, 14, is indeed not a socket:

```
# lsof -p 14103
COMMAND     PID USER   FD      TYPE             DEVICE SIZE/OFF    NODE NAME
syslog-ng 14103 root  cwd       DIR               0,17      480    4854 /run
syslog-ng 14103 root  rtd       DIR              252,0     4096       2 /
syslog-ng 14103 root  txt       REG              252,0    14800 3440349 /usr/sbin/syslog-ng
syslog-ng 14103 root  mem       REG              252,0    10264 3837474 /usr/lib64/syslog-ng/liblinux-kmsg-format.so
syslog-ng 14103 root  mem       REG              252,0    43480 3837405 /usr/lib64/syslog-ng/libsyslogformat.so
syslog-ng 14103 root  mem       REG              252,0    73528 3837439 /usr/lib64/syslog-ng/libaffile.so
syslog-ng 14103 root  mem       REG              252,0    40576  921814 /lib64/libwrap.so.0.7.6
syslog-ng 14103 root  mem       REG              252,0   116256 3837438 /usr/lib64/syslog-ng/libafsocket-tls.so
syslog-ng 14103 root  mem       REG              252,0    14360 3837473 /usr/lib64/syslog-ng/libsystem-source.so
syslog-ng 14103 root  mem       REG              252,0    10216 3837444 /usr/lib64/syslog-ng/libconfgen.so
syslog-ng 14103 root  mem       REG              252,0    84600 3579523 /lib64/libresolv-2.20.so
syslog-ng 14103 root  mem       REG              252,0    22704 3579525 /lib64/libnss_dns-2.20.so
syslog-ng 14103 root  mem       REG              252,0    47384 3579527 /lib64/libnss_files-2.20.so
syslog-ng 14103 root  mem       REG              252,0    88472  921816 /lib64/libz.so.1.2.8
syslog-ng 14103 root  mem       REG              252,0    18808 3848190 /lib64/libuuid.so.1.3.0
syslog-ng 14103 root  DEL       REG              252,0          2786442 /var/tmp/portage/dev-libs/openssl-1.0.2d/image/usr/lib64/libcrypto.so.1.0.0
syslog-ng 14103 root  DEL       REG              252,0          2786446 /var/tmp/portage/dev-libs/openssl-1.0.2d/image/usr/lib64/libssl.so.1.0.0
syslog-ng 14103 root  mem       REG              252,0    14416 3579515 /lib64/libdl-2.20.so
syslog-ng 14103 root  mem       REG              252,0   444472 3581759 /lib64/libpcre.so.1.2.4
syslog-ng 14103 root  mem       REG              252,0    18640  793022 /usr/lib64/libevtlog.so.0.0.0
syslog-ng 14103 root  mem       REG              252,0     5896  801731 /usr/lib64/libgthread-2.0.so.0.4200.2
syslog-ng 14103 root  mem       REG              252,0    14376  801641 /usr/lib64/libgmodule-2.0.so.0.4200.2
syslog-ng 14103 root  mem       REG              252,0    84760 3579530 /lib64/libnsl-2.20.so
syslog-ng 14103 root  mem       REG              252,0    31536 3579517 /lib64/librt-2.20.so
syslog-ng 14103 root  mem       REG              252,0  1656224 3579536 /lib64/libc-2.20.so
syslog-ng 14103 root  mem       REG              252,0   125529 3579519 /lib64/libpthread-2.20.so
syslog-ng 14103 root  mem       REG              252,0  1258296  801729 /usr/lib64/libglib-2.0.so.0.4200.2
syslog-ng 14103 root  mem       REG              252,0   653848 3440584 /usr/lib64/libsyslog-ng-3.6.so.0.0.0
syslog-ng 14103 root  mem       REG              252,0   140520 3579535 /lib64/ld-2.20.so
syslog-ng 14103 root  mem       REG              252,0    16384 3828185 /var/lib/syslog-ng/syslog-ng.persist
syslog-ng 14103 root  mem       REG              252,0    26244  791449 /usr/lib64/gconv/gconv-modules.cache
syslog-ng 14103 root    0r      CHR                1,3      0t0    3683 /dev/null
syslog-ng 14103 root    1w      CHR                1,3      0t0    3683 /dev/null
syslog-ng 14103 root    2w      CHR                1,3      0t0    3683 /dev/null
syslog-ng 14103 root    3u  a_inode               0,10        0    3681 [eventpoll]
syslog-ng 14103 root    4w     FIFO                0,9      0t0 5934841 pipe
syslog-ng 14103 root    6u  a_inode               0,10        0    3681 [eventfd]
syslog-ng 14103 root    7u     unix 0x0000000000000000      0t0 5934844 /var/run/syslog-ng.ctl type=STREAM
syslog-ng 14103 root    8u  a_inode               0,10        0    3681 [eventfd]
syslog-ng 14103 root    9u  a_inode               0,10        0    3681 [eventfd]
syslog-ng 14103 root   10u  a_inode               0,10        0    3681 [eventfd]
syslog-ng 14103 root   11u  a_inode               0,10        0    3681 [eventfd]
syslog-ng 14103 root   12u      REG              252,0    16384 3828185 /var/lib/syslog-ng/syslog-ng.persist
syslog-ng 14103 root   13u     unix 0x0000000000000000      0t0 5934859 /dev/log type=DGRAM
syslog-ng 14103 root   14r      CHR               1,11      0t0    3688 /dev/kmsg
syslog-ng 14103 root   15u  a_inode               0,10        0    3681 [eventpoll]
syslog-ng 14103 root   16u  a_inode               0,10        0    3681 [eventfd]
#
```

This issue occurs with syslog-ng 3.6.4 and Gentoo's default config:

```
@version: 3.6
# $Id$
#
# Syslog-ng default configuration file for Gentoo Linux

# https://bugs.gentoo.org/show_bug.cgi?id=426814
@include "scl.conf"

options {
        threaded(yes);
        chain_hostnames(no);

        # The default action of syslog-ng is to log a STATS line
        # to the file every 10 minutes.  That's pretty ugly after a while.
        # Change it to every 12 hours so you get a nice daily update of
        # how many messages syslog-ng missed (0).
        stats_freq(43200);
        # The default action of syslog-ng is to log a MARK line
        # to the file every 20 minutes.  That's seems high for most
        # people so turn it down to once an hour.  Set it to zero
        # if you don't want the functionality at all.
        mark_freq(3600);
};

source src { system(); internal(); };

destination messages { file("/var/log/messages"); };

# By default messages are logged to tty12...
destination console_all { file("/dev/tty12"); };
# ...if you intend to use /dev/console for programs like xconsole
# you can comment out the destination line above that references /dev/tty12
# and uncomment the line below.
#destination console_all { file("/dev/console"); };

log { source(src); destination(messages); };
log { source(src); destination(console_all); };
```

**Comment by keytoaster** [comment] 2015-09-03 16:35
I just realized the syscall sequence is the same during normal operation, with the difference being that it blocks on epoll_wait(). In my case, it doesn't block (for long) and immediately loops again, causing a high load.

**Comment by bazsi** [comment] 2015-09-03 20:58
Seems that fd14 is readable and then we don't fetch data, causing it to
become readable again.

This seems to be a /dev/kmsg issue, which you can probably work around by
using /proc/kmsg instead.

Until then can you file a bug report pls?

**Comment by dnsjts** [comment] 2015-09-11 17:57
@bazsi , are you sure about this explanation?
I'm asking this, because fd13 is dangerously close to fd14, which is a dgram socket (therefore the `setsockopt` is a relevant syscall), and when we save an fd to the `PersistConfig`, we add one to it.
Maybe we forgot to subtract one somewhere.

(And sorry for the doubt, this is just a theory, and I can't really confirm it, nor supress my inner voice.)

**Comment by bazsi** [comment] 2015-09-12 05:43
Of course I am not sure. That substraction has existed in the codebase for
a long while now, and I cant recall a related change there.

Btw. we add/substract one in order to detect extremal values (eg. Not an
fd), as fd zero is perfectly normal and valid otherwise.

**Comment by u2yg** [comment] 2015-09-17 12:06
It's hard to reproduce, so I think it would be useful for future reference if you could attach a core dump if it's not too inconvenient for you.

**Comment by bazsi** [comment] 2015-09-17 14:40
I just found a similar bug that could be related and showed the same
symptoms. It's difficult to tell if it's the same problem though, the
strace you posted only contains a single thread, so using -f to attach to
all the threads would be useful.

If you can make syslog-ng to dump core, it might help pinpoint the problem
though. You can send that via email.

Here's the branch I was just mentioning:
https://github.com/balabit/syslog-ng/pull/702



-- 
Bazsi

**Comment by keytoaster** [comment] 2015-09-18 18:56
I will provide a core dump and the strace output of all threads the next time the issue occurs. Ironically, it has been running fine for the last two weeks.

**Comment by ssbertilson** [comment] 2015-09-22 01:53
How do I get it to generate a core dump (I'm on Gentoo/Calculate)?  For now I'll e-mail a strace -f -tt which I ran for a while while it was spinning just before I sent it an abort signal.  It doesn't seem to have dropped a core, can do that if you tell me how.

**Comment by ssbertilson** [comment] 2015-09-22 02:02
OK, easier than finding your e-mail:
http://umn.edu/~ssb/syslog-ng.str.gz
This was a quick catch while it was already running which seems like the best I can do until we figure out how to cause this.

**Comment by ssbertilson** [comment] 2015-09-22 03:06
Some progress in recreating the problem.  Ran it under strace with enable-core.
Look in: http://umn.edu/~ssb/syslog-ng/
which has:
syslog-ng-emerge-info
syslog-ng-from-start.str.gz
syslog-ng.core.gz
It seems that after a few HUPs (this instance took several with delays of several seconds between) it would go off spinning.  Got this in /var/log/messages at the time of the HUP that triggered the problem:
Sep 21 21:43:02 XX syslog-ng[7881]: Configuration reload request received, reloading configuration;
Sep 21 21:45:41 XX syslog-ng[7881]: I/O error occurred while reading; fd='14', error='Broken pipe (32)'

My config is stock Gentoo except for allowing read on log files:
@version: 3.6
# $Header: /var/cvsroot/gentoo-x86/app-admin/syslog-ng/files/3.6/syslog-ng.conf.gentoo,v 1.1 2014/11/09 08:10:43 mr_bones_ Exp $
#
# Syslog-ng default configuration file for Gentoo Linux

# https://bugs.gentoo.org/show_bug.cgi?id=426814
@include "scl.conf"

options { 
        threaded(yes);
        chain_hostnames(no); 

        # The default action of syslog-ng is to log a STATS line
        # to the file every 10 minutes.  That's pretty ugly after a while.
        # Change it to every 12 hours so you get a nice daily update of
        # how many messages syslog-ng missed (0).
        stats_freq(43200); 
        # The default action of syslog-ng is to log a MARK line
        # to the file every 20 minutes.  That's seems high for most
        # people so turn it down to once an hour.  Set it to zero
        # if you don't want the functionality at all.
        mark_freq(3600); 
        perm(0644);
};

source src { system(); internal(); };

destination messages { file("/var/log/messages"); };

# By default messages are logged to tty12...
destination console_all { file("/dev/tty12"); };
# ...if you intend to use /dev/console for programs like xconsole
# you can comment out the destination line above that references /dev/tty12
# and uncomment the line below.
#destination console_all { file("/dev/console"); };

log { source(src); destination(messages); };
log { source(src); destination(console_all); };

$ syslog-ng -V
syslog-ng 3.6.4
Installer-Version: 3.6.4
Revision: 
Compile-Date: Aug  5 2015 08:15:41
Available-Modules: afsocket-notls,dbparser,afuser,affile,linux-kmsg-format,confgen,csvparser,basicfuncs,cryptofuncs,system-source,afstomp,syslogformat,graphite,afprog,pseudofile,afsocket,afsocket-tls
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off

**Comment by u2yg** [comment] 2015-09-22 09:23
Thank you for the addenda. The relation to HUPs is promising, I have encountered various reload related segfault and file system corruption issues in the past days, but sadly I can't reproduce them.

Unfortunately, your web server returns "Search error" for all of the above URL. Could you please have a look?

**Comment by ssbertilson** [comment] 2015-09-22 12:30
I just ran a wget against each of these with no problems:
http://umn.edu/~ssb/syslog-ng/syslog-ng.core.gz
http://umn.edu/~ssb/syslog-ng/syslog-ng-emerge-info
http://umn.edu/~ssb/syslog-ng/syslog-ng-from-start.str.gz

No special permissions or login required.
You should be able to see the directory too:
http://umn.edu/~ssb/syslog-ng/

**Comment by u2yg** [comment] 2015-09-22 12:38
Thanks, I could download it now. The outage was probably only temporary. We'll report back to you when this issue gets rescheduled or someone volunteers to have a look.

**Comment by ssbertilson** [comment] 2015-09-22 12:48
I can easily go back to 3.4.8 and should be able to test 3.7.1 since both of those have ebuilds for Gentoo if that would be helpful.  I can probably hack an ebuild to build from the git if that would be better.

I've been seeing this on multiple Gentoo/Calculate laptops for a few weeks now.

**Comment by u2yg** [comment] 2015-09-22 12:58
Well, I guess if it's not too much work for you and you seem to have good luck in reproducing the issue, it would help if we could bisect it a bit. So for starters, it can be promising if you could check whether 3.4.8 fails. I'm not sure whether you could automate it well enough to be able to hook it up to git bisect by a script involving kill and grep, but that would sure make life much easier.

**Comment by ssbertilson** [comment] 2015-09-28 23:05
The problem hasn't occurred as often as it had been on the system with 3.6.4, just once since I was preparing to downgrade to 3.4.8.  I had tried to recreate the problem and it wasn't cooperating under 3.6.4 so after another day or 2 I downgraded the host which had been encountering the problem the most.  Thus far I haven't seen it happen again.  In a few days I'll try 3.7.1.

**Comment by juhaszviktor** [comment] 2015-09-29 07:58
Thanks!

**Comment by ihrwein** [comment] 2015-10-21 15:08
@ssbertilson did you manage to try 3.7.1?

**Comment by ssbertilson** [comment] 2015-10-21 16:12
Thanks for the reminder.

I had downgraded my most problematic machine to 3.4.8 and hadn't had any
problems, but didn't get around to trying the newer version.  Upgrading to
3.7.1 now.

**Comment by ihrwein** [comment] 2015-12-01 14:33
@ssbertilson did you managed to upgrade?

**Comment by ssbertilson** [comment] 2015-12-01 15:19
Yes, have been running 3.7.1 (Gentoo -r1) since November 15th and it hasn't
gone into 100% CPU mode since then.

**Comment by ihrwein** [comment] 2015-12-02 15:11
Good news :)

Then I think we can close this issue. Could you press the button, please? :)

**Comment by ssbertilson** [comment] 2015-12-02 19:47
Agreed, seems like we're past the problem now.

**Closed** 2015-12-02 19:54 UTC
Labels: bug, hard, ready

**Comment by ihrwein** [comment] 2015-12-02 19:58
I closed it. Thanks for the cooperation :)

**Comment by muahao** [comment] 2016-09-14 04:53
@bazsi    Hello,  I appeared this problem at syslog-ng-3.5.6, and it also appeared at syslog-ng-3.6.4, which verison solved this problem ?which version you propose? Thanks a lot

**Comment by bazsi** [comment] 2016-09-14 04:58
The thread above concluded on 3.7.1 so anything past that. The latest version us 3.8.1

**Comment by muahao** [comment] 2016-09-14 05:19
@bazsi  You mean 3.7.1 solved this problem ?Can you tell me which patch fix this problem?

**Comment by bazsi** [comment] 2016-09-14 06:57
Honestly, I can't remember, but this would be my candidate, and that's what
PR #702 references above.

351d92d0e37fc95b15fb3abb7850ebb06ffb4335


-- 
Bazsi

**Comment by muahao** [comment] 2016-12-15 09:21
hello,I find at syslog-ng-3.5 and syslog-ng-3.6 ,the syslog-ng will default read from /dev/kmsg even if when I don't use file ("/proc/kmsg" program_override("kernel: ")); in source{  },

when I use docker container ,I find that containers all will read /dev/kmsg , this will have some problems.

so how can I specify don't read /dev/kmsg ?
