### ISSUE TITLE
cross compilation for arm: question about linkage

### ISSUE THREAD

**Issue by srikanthpadava** [balabit/syslog-ng#1969] opened 2018-04-05 15:52 UTC
#**# Version of syslog-ng**
3.14

## **Platform**

**(Name and version of OS)**
build system is Ubuntu 16 (x86)
cross compiling for arm

**Problem:**

As mentioned in the title i am trying to cross compile syslog-ng for arm from the sources.
I cannot use dynamic-linking option of the configure script as not all dynamic libraries required by syslog-ng (like libsecret-storage, libevtlog) will be present on the target. But some (like glib-2.0, libpthread, libpcre) are present. 

So i need to link statically some libraries like libevtlog, libsecret-storage and dynamically link others. 
When i use enable-dynamic-linking it tries to link all required libraries dynamically (.so)
When i use enable-mixed-mode it tries to link for eg glib-2.0 statically which i do not want. it is present on the target.

Could any one suggest me how to force the autotools to statically some libraries.

The following is the objdump of the syslog-ng binary i was able to generate using enable-dynamic-linking. But it would not run on the target as libsyslog-ng.so, libsecret-storage.so, libevtlog.so would not exist on the target.

![image](https://user-images.githubusercontent.com/38109174/38376822-c3d101a2-38f9-11e8-8c49-9ad8095a89e1.png)

ps: I can provide the configure.ac, configure options that i am using and the Makefile.am if required.

Thank you.
Srik

**Comment by Kokan** [comment] 2018-04-05 16:30
Hello,
Please provide those options :)

Also I just wanted to make a note, that `libsecret-storage` you do not want to statically link (see https://github.com/balabit/syslog-ng/pull/1888).

**Comment by furiel** [comment] 2018-04-05 16:31
Hi @srikanthpadava,
I'm not sure how can you enforce such linking, but...

the linking of exactly these two modules are buggy in 3.14. Both of these are shipped with syslog-ng, they should not (must not) be available on the target system.

The eventlog is fixed here: https://github.com/balabit/syslog-ng/pull/1915.
The secret storage is fixed here: https://github.com/balabit/syslog-ng/pull/1954

Maybe if you try to checkout the latest-greatest version of syslog-ng from github, it would work for you. Or you can wait for 3.15 which will contain those patches. It will be released in a few weeks.

**Comment by srikanthpadava** [comment] 2018-04-10 09:47
@furiel, @kokan: Thanks for the responses,

I have followed the  hints given by @furiel  and i was able to finally cross compile syslog-ng.
But when i objdump the generated syslog-ng binary the evtlog and secret-storage libraries are still dynamically linked and not statically, which should have been the case.
 

![image](https://user-images.githubusercontent.com/38109174/38549266-f2ed241c-3cb3-11e8-8d2e-b38265f28806.png)


I am attaching the configure.ac and the lib/Makefile.am (i had to rename all the files to have an extension .log as otherwise i could not upload the original files). I can provide any other files if necessary. 
I hope you could help me understand why the  two libraries are still dynamically linked.

[configure.log](https://github.com/balabit/syslog-ng/files/1894053/configure.log)
[Makefile.log](https://github.com/balabit/syslog-ng/files/1894054/Makefile.log)
[syslog-ng.log](https://github.com/balabit/syslog-ng/files/1894055/syslog-ng.log)

**Comment by furiel** [comment] 2018-04-10 11:01
For libevtlog you are absolutely right, it should be statically linked. The reason it is dynamically linked comes from a licensing issue.

As for libsecretstorage, it is dynamically linked by design for now. Again, it is not an external dependency to libsyslog-ng as in terms any other libs from your list (libssl, glib, etc). It is a syslog-ng module, and it is shipped with syslog-ng. Any syslog-ng modules that use secret storage - currently libsyslog-ng, libafsocket needs to link to it. As libafsocket does not link statically with libsyslog-ng, it is the same with libsecretstorage.

Does this answer your question? I am very interested in the use case why you need to link with libsecretstorage statically. It is possible we miss something. (Please don't be afraid to be very descriptive in the explanation, I have little experience in cross compiling :( ).

**Comment by srikanthpadava** [comment] 2018-04-10 12:47
I had closed by mistake earlier. So i reopened again.

**Comment by srikanthpadava** [comment] 2018-04-10 15:46
@furiel 

_For libevtlog you are absolutely right, it should be statically linked. The reason it is dynamically linked comes from a licensing issue_
>>ok so it means that there is no way i can link it statically.

_Any syslog-ng modules that use secret storage - currently libsyslog-ng, libafsocket needs to link to it. As libafsocket does not link statically with libsyslog-ng, it is the same with libsecretstorage._
>>Yes this answers my question.

There is no specific serious use case as to why i am trying to avoid having these libraries linked to syslog-ng dynamically. I am just trying to not bring 3rd party libraries which  are not used system/project wide into our target, rather bring integrated to the binary itself. (to avoid extra internal review process for every library we add to the target :-))

But now it is clear to me why it is as it is the case now.

Thanks

**Comment by srikanthpadava** [comment] 2018-04-11 07:34
@gaborznagy 
 My questions have been answered.

Please close the ticket.

**Closed** 2018-04-11 07:46 UTC
Labels: compile related
