### ISSUE TITLE
inline Python code: ' in comment generates syntax error

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2317] opened 2018-09-28 13:28 UTC
# syslog-ng

## Version of syslog-ng

git snapshot from yesterday

## Platform

CentOS 7

# Issue

## Failure

While testing the Python parser.

If there is a ' in a comment, like in:
```
# Don't do something
```
Then syslog-ng does not start, but gives an error message and the ^^^ is at the wrong place:
```
[2018-09-28T15:13:52.655555] Module loaded and initialized successfully; module='mod-java'
[2018-09-28T15:13:52.655701] Finishing include; content='block destination elasticsearch2() at /usr/share/syslog-ng/include/scl/elasticsearch/plugin.conf:59', depth='2'
[2018-09-28T15:13:52.671001] Module loaded and initialized successfully; module='mod-python'
Error parsing Python code, syntax error, unexpected $end, expecting LL_BLOCK in /etc/syslog-ng/conf.d/suricata.conf:
56      """
57      
58      import socket
59      
60      class SngResolver(object):
61---->     def parse(self, log_message):
61----> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
62              """
63              Resolves IP to hostname
64              """
65      
66              # Don't resolve DNS transactions

Included from /etc/syslog-ng/syslog-ng.conf:
63      log { source(s_sys); filter(f_cron); destination(d_cron); };
64      
65      
66      # Source additional configuration files (.conf extension only)
67      @include "/etc/syslog-ng/conf.d/*.conf"
68----> 
68----> ^
69      
70      # vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:
```

## Configuration

```
[...]
parser p_resolver {
    python(
        class("SngResolver")
    );
};

python {

"""
simple syslog-ng Python parser example
resolves IP to hostname
"""

import socket

class SngResolver(object):
    def parse(self, log_message):
        """
        Resolves IP to hostname
        """

        # Don't resolve DNS transactions
        dest_port = log_message['suricata.dest_port']
        if dest_port == '53':
            return True
[...]
```
If I use """ for comment instead of #, the ' does not cause a problem any more. The same Python code runs just fine when used in a .py file instead of inline, and pylint does not complain about it either.

**Comment by Kokan** [comment] 2018-09-28 13:41
For version if you want to provide you can always write the git hash :)
Could you please post a minimalist configuration that still reproduces the issue ? (not just a partial config)

Also for me the `pyton {} ` does not seems correct. I think the `python` block should be named.
```
python something {
#code
};
```

**Comment by czanik** [comment] 2018-09-28 13:57
Sorry, I have no idea about the git hash (I update git more often than I build packages for CentOS).
It is an almost complete config, expected to be dropped into /etc/syslog-ng/conf.d
the problematic line is:
```
        # Don't do anything just return true
```
If I replace it with:
```
        """ Don't do anything just return true """
```
or
```
        # Do not do anything just return true
```
it works just fine.

```
[root@centos7 conf.d]# cat suricata.conf
parser p_resolver {
    python(
        class("SngResolver")
    );
};

python {

import socket

class SngResolver(object):
    def parse(self, log_message):
        """
        Resolves IP to hostname
        """
        # Don't do anything just return true
        return True
};

log {
    source(src);
    parser(p_resolver);
    destination(d_elastic);
};
[root@centos7 conf.d]# syslog-ng -s
Error parsing Python code, syntax error, unexpected $end, expecting LL_BLOCK in /etc/syslog-ng/conf.d/suricata.conf:
9       import socket
10      
11      class SngResolver(object):
12          def parse(self, log_message):
13              """
14---->         Resolves IP to hostname
14----> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15              """
16              # Don't do anything just return true
17              return True
18      };
19      

Included from /etc/syslog-ng/syslog-ng.conf:
63      log { source(s_sys); filter(f_cron); destination(d_cron); };
64      
65      
66      # Source additional configuration files (.conf extension only)
67      @include "/etc/syslog-ng/conf.d/*.conf"
68----> 
68----> ^
69      
70      # vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:
```

**Comment by Kokan** [comment] 2018-09-28 17:06
But in syslog-ng grammar the other includes, and the root config could change your snippet behaviour.
Just an example:
```
@version: 3.17

block root python() { };

python {
#bla
};
```
It won't be a valid configuration, saying something like this:
`Error parsing block reference, syntax error, unexpected '{', expecting '(' in dummy.conf:`
(Of course the issue probably not intentional opposed to my example.)

But I created such config:
```
@version: 3.17

python {
#b'la
};
```
And it does not work. Just as you wrote. First I tried to "fix" it by closing the `'`.
```
...
python {
#b'la'
};
```

The whole stuff inside the `{ }` is a *block* in the configuration. Where most of the configuration rules do not apply. For example it does not differentiate commented and un-commented text.
The usual string representation is known by this *block* state, in this case it sees as a string is started with `'` but never closed, therefore it is not a valid config.

The solution is not just as simple as removing this knowledge, because it solves an other corner case like:
```
python {
 print("}");
};
```
A possible solution could be to make the *block* understood the comment section, and do not look for string in them.

Maybe something other solution could work like instead of *block* we could ask the python interpreter if it is a valid python line, when the first invalid python line we got, we could check if it is closing of a block or not. (Maybe this is not a good idea.) The sideeffect would be that the python script is validated when the config is validated.

[off]
About git hash: https://blog.thoughtram.io/git/2014/11/18/the-anatomy-of-a-git-commit.html (this is complex on purpose :))

**Closed** 2018-10-12 08:27 UTC
Labels: bug
