### ISSUE TITLE
UNIX credentials info on FreeBSD

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#271] opened 2014-09-24 10:49 UTC
On Linux, the following configuration snippet correctly extracts UNIX credentials when uning a socket source:

destination d_bla { file("/var/log/bla" template("pid: ${.unix.pid}, uid: ${.unix.uid}, gid: ${.unix.gid}, exe: ${.unix.exe}, cmdline: ${.unix.cmdline}, massage: ${MESSAGE}\n\n")); };
log { source(src); destination(d_bla); };

On the other hand, it does not seem to work on FreeBSD, where only the MESSAGE macro is recorded:

pid: , uid: , gid: , exe: , cmdline: , massage: blabla

**Comment by ihrwein** [comment] 2015-07-20 14:19
@czanik : dou you have a virtualbox image where this problem can be reproduced? I checked the code
but found nothing.

**Comment by ihrwein** [comment] 2015-07-20 15:13
I've got a FreeBSD machine from @czanik where I was able to build syslog-ng from git. For the testing I will need a sample program which sends its credentials.

**Comment by ihrwein** [comment] 2015-07-21 08:10
@czanik We have tested it and this feature works fine on FreeBSD. I think the problem was the you used `logger` to send the logs. We used a specially crafted program to test.

I will close this issue as it is invalid. If you need more information or proof please find me.

**Closed by ihrwein** 2015-07-21 08:10 UTC
Labels: bug, ready
