### ISSUE TITLE
Syslog-ng missed ":" symbol before ${MSG}.

### ISSUE THREAD

**Issue by simpleuser99** [balabit/syslog-ng#1873] opened 2018-02-05 13:45 UTC
# syslog-ng

syslog-ng.x86_64               3.8.1-1.el6

## Version of syslog-ng

```
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision:
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: confgen,redis,date,basicfuncs,linux-kmsg-format,disk-buffer,pseudofile,affile,system-source,dbparser,syslogformat,afstomp,graphite,add-contextual-data,cef,csvparser,afuser,afprog,kvformat,afsocket,cryptofuncs,afmongodb
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: off
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

```

## Platform

CentOs 6.9

# Issue
I have:

> Feb  5 16:30:01 host.loc CROND[48969] (root) CMD (/usr/sbin/logrotate  -f /root/scripts/tmpfs)

Syslog-ng missed ":" symbol before ${MSG}.

I expected:

> Feb  5 16:30:01 host.loc CROND[48969]: (root) CMD (/usr/sbin/logrotate  -f /root/scripts/tmpfs)

Syslog-ng do not missed ":" symbol  before ${MSG}.

My config:

> @version:3.8
> @include "scl.conf"
> 
> options {
>     flush_lines (5000);
>     time_reopen (10);
>     log_msg_size(10MB);
>     log_fifo_size (100000);
>     chain_hostnames (off);
>     use_dns (no);
>     use_fqdn (yes);
>     create_dirs (no);
>     keep_hostname (yes);
>     use_uniqid (yes);
> 
> };
> 
> source s_int{
>     udp(ip(127.0.0.1) port(416));
>     tcp(ip(127.0.0.1) port(416));
> };
> 
> destination d_to_syslog { syslog("10.10.10.10" transport("tcp") port(415) ); };
> log { source(s_int); destination(d_to_syslog); };

**Comment by simpleuser99** [comment] 2018-02-12 09:02
Does anyone know how to solve my problem?

**Comment by bazsi** [comment] 2018-02-12 12:17
I can't see how you get that line with the ":" removed, as you only have
syslog() destinations in the sample you have provided. The ":" should be
coming from the $MSGHDR macro, as a complete template looks like this:

file("/var/log/messages" template("$DATE $HOST $MSGHDR$MSG\n"));

at least with configuration versions above 3.0, where the $MSG macro was
changed not to contain the MSGHDR value.

I hope this helps, and please provide additional details if it doesn't.


-- 
Bazsi

**Comment by gaborznagy** [comment] 2018-02-12 13:04
Hello!

I have just looked into your issue.
I can see the same behaviour on the latest version of syslog-ng built from source.
What I see first is that your log message is not conforming to the [BSD syslog format](https://tools.ietf.org/html/rfc3164#section-4.1).
Specifically the [timestamp](https://tools.ietf.org/html/rfc3164#section-4.1.2) part: 
*"If the day of the month is less than 10, then it MUST be represented as a space and then the   number."*
Your log message parsed incorrectly due to this and it parsed everything after the first word into the $MSG part.
If I add an extra space in the timestamp I can see the following:
`114 <13>1 2018-02-05T16:30:01+01:00 localhost CROND 48969 - - (root) CMD (/usr/sbin/logrotate -f /root/scripts/tmpfs)`
The header part parsed correctly.

You reported that this was working before and you expect that a ":" would be seen on the output, right?

**Comment by simpleuser99** [comment] 2018-02-20 06:51
@gaborznagy 
I do not know that it work before. I do not use syslog-ng before. This is my first expirence to use sysloog-ng. Yes I expect that a ":" would be seen on the output.

**Comment by gaborznagy** [comment] 2018-02-20 14:31
Sorry for misunderstanding, but I thought your issue is a report about a regression.

I would not expect that syslog-ng would automatically enrich your log message with a ':'.
Syslog-ng **parses** the incoming messages and **formats** the output based on the destination.
If the incoming log message contains the ":" it will be in the outgoing message, if not, syslog-ng will not add it to the message.
What is your expectation about the output format, why is the ':' necessary?
Is it expected on the destination side where syslog-ng is sending the log messages?
If the format of your incoming log message is correct, syslog-ng can parse the log message without problem. The ':' character or the PROGRAM and PID fields are not mandatory in the log message.


What you *expect* would be either a **template**(for formatting) or a **rewrite rule** to modify/extend your log message.

About the default parsing see:
https://syslog-ng.com/documents/html/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/parser-syslog.html
Some information about [templates.](https://syslog-ng.com/documents/html/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/customizing-message-format.html)
Description of  [rewrite rules](https://syslog-ng.com/documents/html/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/modifying-messages.html
).

Please note my previous comment about the invalid message format that causes an invalid message parsing:
> What I see first is that your log message is not conforming to the BSD syslog format.
> Specifically the timestamp part:
> "If the day of the month is less than 10, then it MUST be represented as a space and then the number."
> Your log message parsed incorrectly due to this and it parsed everything after the first word into the $MSG part.

You can use a template for debugging message parsing, similary to @bazsi's previous reply:
`file("/var/log/messages" template("$PRI $DATE $HOST $MSGHDR $MSG\n"));`

**Comment by gaborznagy** [comment] 2018-04-09 10:55
I'm closing this issue due to my previous statements and inactivity.

**Closed by gaborznagy** 2018-04-09 10:55 UTC
Labels: question
