### ISSUE TITLE
diskq valgrind issues

### ISSUE THREAD

**Issue by bazsi** [balabit/syslog-ng#946] opened 2016-02-21 21:53 UTC
The diskq unit tests fail under valgrind, you can reproduce these using "make check-valgrind".
# FAIL: modules/diskq/tests/test_diskq

==24261== Memcheck, a memory error detector
==24261== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==24261== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==24261== Command: ./modules/diskq/tests/test_diskq
==24261== 
[2016-02-21T22:50:29.727886] Plugin module not found in 'module-path'; module-path='(null)', module='builtin-serializer'
==24261== Syscall param pwrite64(buf) points to uninitialised byte(s)
==24261==    at 0x58546A3: __pwrite_nocancel (syscall-template.S:81)
==24261==    by 0x504F539: pwrite_strict (qdisk.c:94)
==24261==    by 0x504FAB8: qdisk_push_tail (qdisk.c:244)
==24261==    by 0x504D5A7: _write_message (logqueue-disk.c:295)
==24261==    by 0x504F080: _push_tail (logqueue-disk-reliable.c:257)
==24261==    by 0x504CD79: _push_tail (logqueue-disk.c:66)
==24261==    by 0x4068D0: log_queue_push_tail (logqueue.h:100)
==24261==    by 0x406B1E: feed_some_messages (queue_utils_lib.c:60)
==24261==    by 0x4043EB: testcase_ack_and_rewind_messages (test_diskq.c:138)
==24261==    by 0x404A11: main (test_diskq.c:310)
==24261==  Address 0x7b46387 is 135 bytes inside a block of size 512 alloc'd
==24261==    at 0x4C2DD9F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24261==    by 0x5584637: g_realloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24261==    by 0x559FA96: g_string_maybe_expand (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24261==    by 0x559FDB6: g_string_insert_len (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24261==    by 0x52A8C27: serialize_string_archive_write_bytes (serialize.c:169)
==24261==    by 0x52A87EE: serialize_archive_write_bytes (serialize.c:75)
==24261==    by 0x52A8EED: serialize_write_blob (serialize.c:245)
==24261==    by 0x52E7B86: _write_payload (nvtable-serialize.c:427)
==24261==    by 0x52E7BFC: nv_table_serialize (nvtable-serialize.c:440)
==24261==    by 0x52E4914: log_msg_serialize (logmsg-serialize.c:79)
==24261==    by 0x504D58D: _write_message (logqueue-disk.c:294)
==24261==    by 0x504F080: _push_tail (logqueue-disk-reliable.c:257)
==24261==    by 0x504CD79: _push_tail (logqueue-disk.c:66)
==24261==    by 0x4068D0: log_queue_push_tail (logqueue.h:100)
==24261==    by 0x406B1E: feed_some_messages (queue_utils_lib.c:60)
==24261==    by 0x4043EB: testcase_ack_and_rewind_messages (test_diskq.c:138)
==24261==    by 0x404A11: main (test_diskq.c:310)
==24261== 
==24261== Thread 2:
==24261== Syscall param pwrite64(buf) points to uninitialised byte(s)
==24261==    at 0x58546C3: ??? (syscall-template.S:81)
==24261==    by 0x504F539: pwrite_strict (qdisk.c:94)
==24261==    by 0x504FAB8: qdisk_push_tail (qdisk.c:244)
==24261==    by 0x504D5A7: _write_message (logqueue-disk.c:295)
==24261==    by 0x504F080: _push_tail (logqueue-disk-reliable.c:257)
==24261==    by 0x504CD79: _push_tail (logqueue-disk.c:66)
==24261==    by 0x403DE5: log_queue_push_tail (logqueue.h:100)
==24261==    by 0x4045C3: threaded_feed (test_diskq.c:190)
==24261==    by 0x55A5964: g_thread_proxy (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24261==    by 0x584B6A9: start_thread (pthread_create.c:333)
==24261==    by 0x5B68EEC: clone (clone.S:109)
==24261==  Address 0x83a3eb7 is 55 bytes inside a block of size 512 alloc'd
==24261==    at 0x4C2DD9F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24261==    by 0x5584637: g_realloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24261==    by 0x559FA96: g_string_maybe_expand (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24261==    by 0x559FDB6: g_string_insert_len (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24261==    by 0x52A8C27: serialize_string_archive_write_bytes (serialize.c:169)
==24261==    by 0x52A87EE: serialize_archive_write_bytes (serialize.c:75)
==24261==    by 0x52A8EED: serialize_write_blob (serialize.c:245)
==24261==    by 0x52E7B86: _write_payload (nvtable-serialize.c:427)
==24261==    by 0x52E7BFC: nv_table_serialize (nvtable-serialize.c:440)
==24261==    by 0x52E4914: log_msg_serialize (logmsg-serialize.c:79)
==24261==    by 0x504D58D: _write_message (logqueue-disk.c:294)
==24261==    by 0x504F080: _push_tail (logqueue-disk-reliable.c:257)
==24261==    by 0x504CD79: _push_tail (logqueue-disk.c:66)
==24261==    by 0x403DE5: log_queue_push_tail (logqueue.h:100)
==24261==    by 0x4045C3: threaded_feed (test_diskq.c:190)
==24261==    by 0x55A5964: g_thread_proxy (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24261==    by 0x584B6A9: start_thread (pthread_create.c:333)
==24261==    by 0x5B68EEC: clone (clone.S:109)
==24261== 
Feed speed: 4524.59
==24261== 
==24261== HEAP SUMMARY:
==24261==     in use at exit: 455,036 bytes in 3,782 blocks
==24261==   total heap usage: 2,039,569 allocs, 2,035,787 frees, 298,391,497 bytes allocated
==24261== 
==24261== LEAK SUMMARY:
==24261==    definitely lost: 0 bytes in 0 blocks
==24261==    indirectly lost: 0 bytes in 0 blocks
==24261==      possibly lost: 0 bytes in 0 blocks
==24261==    still reachable: 455,036 bytes in 3,782 blocks
==24261==         suppressed: 0 bytes in 0 blocks
==24261== Reachable blocks (those to which a pointer was found) are not shown.
==24261== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==24261== 
==24261== For counts of detected and suppressed errors, rerun with: -v
==24261== Use --track-origins=yes to see where uninitialised values come from
==24261== ERROR SUMMARY: 101200 errors from 2 contexts (suppressed: 0 from 0)
# FAIL: modules/diskq/tests/test_diskq_full

==24281== Memcheck, a memory error detector
==24281== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==24281== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==24281== Command: ./modules/diskq/tests/test_diskq_full
==24281== 
[2016-02-21T22:50:30.725788] Plugin module not found in 'module-path'; module-path='(null)', module='builtin-serializer'
==24281== 
==24281== HEAP SUMMARY:
==24281==     in use at exit: 1,442,002 bytes in 9,543 blocks
==24281==   total heap usage: 42,023 allocs, 32,480 frees, 4,167,079 bytes allocated
==24281== 
==24281== 536,000 bytes in 1,000 blocks are definitely lost in loss record 725 of 726
==24281==    at 0x4C2BBCF: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24281==    by 0x5584578: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24281==    by 0x52E3356: log_msg_alloc (logmsg.c:1081)
==24281==    by 0x52E34A0: log_msg_new (logmsg.c:1129)
==24281==    by 0x405D2D: feed_some_messages (queue_utils_lib.c:54)
==24281==    by 0x403B47: test_diskq_become_full (test_diskq_full.c:77)
==24281==    by 0x403C86: main (test_diskq_full.c:100)
==24281== 
==24281== 536,000 bytes in 1,000 blocks are definitely lost in loss record 726 of 726
==24281==    at 0x4C2BBCF: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24281==    by 0x5584578: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24281==    by 0x52E3356: log_msg_alloc (logmsg.c:1081)
==24281==    by 0x52E34A0: log_msg_new (logmsg.c:1129)
==24281==    by 0x405D2D: feed_some_messages (queue_utils_lib.c:54)
==24281==    by 0x403B47: test_diskq_become_full (test_diskq_full.c:77)
==24281==    by 0x403C90: main (test_diskq_full.c:101)
==24281== 
==24281== LEAK SUMMARY:
==24281==    definitely lost: 1,072,000 bytes in 2,000 blocks
==24281==    indirectly lost: 0 bytes in 0 blocks
==24281==      possibly lost: 0 bytes in 0 blocks
==24281==    still reachable: 370,002 bytes in 7,543 blocks
==24281==         suppressed: 0 bytes in 0 blocks
==24281== Reachable blocks (those to which a pointer was found) are not shown.
==24281== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==24281== 
==24281== For counts of detected and suppressed errors, rerun with: -v
==24281== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
# FAIL: modules/diskq/tests/test_reliable_backlog

==24301== Memcheck, a memory error detector
==24301== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==24301== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==24301== Command: ./modules/diskq/tests/test_reliable_backlog
==24301== 
==24301== Syscall param pwrite64(buf) points to uninitialised byte(s)
==24301==    at 0x5A5A6A3: __pwrite_nocancel (syscall-template.S:81)
==24301==    by 0x404076: pwrite_strict (qdisk.c:94)
==24301==    by 0x4045D9: qdisk_push_tail (qdisk.c:244)
==24301==    by 0x504D5A7: _write_message (logqueue-disk.c:295)
==24301==    by 0x504F080: _push_tail (logqueue-disk-reliable.c:257)
==24301==    by 0x504CD79: _push_tail (logqueue-disk.c:66)
==24301==    by 0x403E85: log_queue_push_tail (logqueue.h:100)
==24301==    by 0x407627: _prepare_eof_test (test_reliable_backlog.c:134)
==24301==    by 0x40810E: test_over_EOF (test_reliable_backlog.c:221)
==24301==    by 0x408B83: main (test_reliable_backlog.c:381)
==24301==  Address 0x7b44c81 is 49 bytes inside a block of size 256 alloc'd
==24301==    at 0x4C2DD9F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24301==    by 0x5584637: g_realloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24301==    by 0x559FA96: g_string_maybe_expand (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24301==    by 0x559FDB6: g_string_insert_len (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.1)
==24301==    by 0x52A8C27: serialize_string_archive_write_bytes (serialize.c:169)
==24301==    by 0x52A87EE: serialize_archive_write_bytes (serialize.c:75)
==24301==    by 0x52A9202: serialize_write_uint32 (serialize.c:322)
==24301==    by 0x52E7A63: _write_struct (nvtable-serialize.c:400)
==24301==    by 0x52E7BE9: nv_table_serialize (nvtable-serialize.c:438)
==24301==    by 0x52E4914: log_msg_serialize (logmsg-serialize.c:79)
==24301==    by 0x504D58D: _write_message (logqueue-disk.c:294)
==24301==    by 0x504F080: _push_tail (logqueue-disk-reliable.c:257)
==24301==    by 0x504CD79: _push_tail (logqueue-disk.c:66)
==24301==    by 0x403E85: log_queue_push_tail (logqueue.h:100)
==24301==    by 0x407627: _prepare_eof_test (test_reliable_backlog.c:134)
==24301==    by 0x40810E: test_over_EOF (test_reliable_backlog.c:221)
==24301==    by 0x408B83: main (test_reliable_backlog.c:381)
==24301== 
==24301== 
==24301== HEAP SUMMARY:
==24301==     in use at exit: 169,501 bytes in 3,240 blocks
==24301==   total heap usage: 4,331 allocs, 1,091 frees, 299,818 bytes allocated
==24301== 
==24301== LEAK SUMMARY:
==24301==    definitely lost: 0 bytes in 0 blocks
==24301==    indirectly lost: 0 bytes in 0 blocks
==24301==      possibly lost: 0 bytes in 0 blocks
==24301==    still reachable: 169,501 bytes in 3,240 blocks
==24301==         suppressed: 0 bytes in 0 blocks
==24301== Reachable blocks (those to which a pointer was found) are not shown.
==24301== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==24301== 
==24301== For counts of detected and suppressed errors, rerun with: -v
==24301== Use --track-origins=yes to see where uninitialised values come from
==24301== ERROR SUMMARY: 14 errors from 1 contexts (suppressed: 0 from 0)

**Comment by juhaszviktor** [comment] 2016-02-29 11:56
I think we should ignore these valgrind errors. The nvtable has uninitialized bytes by design. The serialization of nvtable writes out the whole memory range of nvtable. This is the root cause of these errors, I think. But if we initialize the memory of whole nvtable it can cause performance issue, as @bazsi  said a few years ago.

**Comment by gaborznagy** [comment] 2018-04-03 13:36
Closing this ticket due to the fact that we have the root cause and stated that we would not like to fix it.

**Closed by gaborznagy** 2018-04-03 13:36 UTC
Labels: compile related
